### ISSUE TITLE
minecraft:torch and minecraft:snow_layer texture failed to load

### ISSUE THREAD

**Issue by cuihua0** [TerraFirmaCraft/TerraFirmaCraft#1846] opened 2022-01-05 12:18 UTC
like this
![2022-01-05 2005](https://user-images.githubusercontent.com/49671528/148215588-ff9b7943-abbc-46a8-b68d-f3be7870ef87.png)

and torch recipe failed to load
i can't use firepit to carft torch

minecraft:1.12.2
MCP:9.42
Forge:14.23.5.2859
TFC:1.7.21.179

**Comment by alcatrazEscapee** [comment] 2022-01-05 18:50
Appears to be a registry replacement failure. Are you using liteloader, sponge, or any custom server software?

**Comment by cuihua0** [comment] 2022-01-06 01:41
liteloader 1.12.2-snapshot, single player, hmcl launcher
![2022-01-06 0930](https://user-images.githubusercontent.com/49671528/148313591-ea4e4390-b38c-4700-9427-a4cc36793eb4.png)
My english is bad. I try to describe it briefly

**Comment by alcatrazEscapee** [comment] 2022-01-06 03:23
> liteloader

Duplicate of #567 then

**Closed as completed by alcatrazEscapee** 2022-01-06 03:23 UTC
Labels: bug, duplicate, mod conflict, wont fix, Version: 1.12.x
