### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DogofSong** [TerraFirmaCraft/TerraFirmaCraft#815] opened 2020-02-13 21:52 UTC
[TFC.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4201386/TFC.zip)

[**Describe](url) the bug**
Make sure to include:
1. What did you expect to happen?
2. What actually happened instead (i.e. what was the bug)
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: 0.X.X.XX
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
[crash-2020-02-13_14.41.01-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4201307/crash-2020-02-13_14.41.01-server.txt) 

I have Journey Map and JEI installed.
I jumped up one block and it just crashed.
Included is the crash report and the world file.

**Comment by alcatrazEscapee** [comment] 2020-02-14 02:27
Duplicate of #805

**Closed as completed by alcatrazEscapee** 2020-02-14 02:27 UTC
Labels: duplicate
