### ISSUE TITLE
Melon plants can grow Melons on top of water.

### ISSUE THREAD

**Issue by Gerbzzz** [TerraFirmaCraft/TerraFirmaCraft#2489] opened 2023-08-04 17:50 UTC
When checking nearby blocks to grow a Melon, Melon Plants next to water can place the Melon on top of the water instead of on a solid block.
![2023-08-04_19 46 09](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/102229362/5b477ef8-a3fb-4456-b914-35db6dbca088)

**Comment by alcatrazEscapee** [comment] 2023-08-05 13:27
What TFC version is this? It should've been fixed in #2391

**Comment by alcatrazEscapee** [comment] 2023-08-09 23:35
Cannot reproduce myself, and no confirmation that this was in a newer version -> it's fixed.

**Closed as completed by alcatrazEscapee** 2023-08-09 23:35 UTC
Labels: duplicate, Version: 1.18.x
