### ISSUE TITLE
TFC Common_setup event phase crash.

### ISSUE THREAD

**Issue by SSilice** [TerraFirmaCraft/TerraFirmaCraft#2393] opened 2023-05-10 19:19 UTC
Weird issue after updating Terrafirmacraft and some other TFC related mods when launching now. never used to happen

[crash-2023-05-10_14.16.37-fml.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11445248/crash-2023-05-10_14.16.37-fml.txt)

**Comment by alcatrazEscapee** [comment] 2023-05-10 20:00
Duplicate of #2392

**Closed as completed by alcatrazEscapee** 2023-05-10 20:00 UTC
Labels: duplicate
