### ISSUE TITLE
sticks deleted instead of turning into torches

### ISSUE THREAD

**Issue by kotoroshinoto** [TerraFirmaCraft/TerraFirmaCraft#1659] opened 2020-12-25 20:17 UTC
I created a firepit; threw a log on, and placed a stick in the input slot.

it set on fire, but instead of generating torches, it just deletes the stick.

was there a  change to this mechanic? If so, how do we make torches now?

**Comment by kotoroshinoto** [comment] 2020-12-25 21:06
seemed to be an odd effect of having liteloader installed. No clue from my side why liteloader does that.

**Comment by alcatrazEscapee** [comment] 2020-12-25 21:27
Duplicate of #567

**Closed as completed by alcatrazEscapee** 2020-12-25 21:27 UTC
Labels: duplicate
