### ISSUE TITLE
Sentence

### ISSUE THREAD

**Issue by AlexRover** [TerraFirmaCraft/TerraFirmaCraft#1593] opened 2020-10-05 17:31 UTC
**Describe the request**
Make sure to include:
1. This would help to better interact with tech mods like Magneticraft, it would also be possible to make more logical re-sets for example for diamond dust from TerraFirmaThings
2. I suggest adding one more method of processing in the anvil "crushing"
2,1 Also the ability to customize and add recipes to the ore rinsing chute

**Meta Info**
 - TFC Version: 1.7.4.162 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

**Comment by alcatrazEscapee** [comment] 2020-10-05 17:54
First off, duplicate of #1583

Okay, my best guess here is you are asking for new recipe mechanics to be added to the anvil and sluice. Which isn't going to happen as it makes no sense to add a completely independent recipe mechanic to the already cluttered anvil, nor does the sluice have any business being a generic recipe block (it's a prospecting tool).

In future, if you have suggestions for new features, the better place for them is our discord, in the `#suggestions` channel, as feature requests on github tend to get ignored or closed as we try and keep this a record of actual issues.

**Closed as completed by alcatrazEscapee** 2020-10-05 17:54 UTC
Labels: duplicate, enhancement
