### ISSUE TITLE
Game suddenly crashed for no apparent reason

### ISSUE THREAD

**Issue by GivensRS** [TerraFirmaCraft/TerraFirmaCraft#1261] opened 2020-05-13 09:45 UTC
Game suddenly crashed for no apparent reason
[spoiler](https://pastebin.com/wFdnn2LX)

I don't know how to reproduce this, i just had melting copper.

 - TFC Version: 1.0.12.141
 - All mods presented at crashlog.

**Comment by BigE1293** [comment] 2020-05-13 11:49
Was this crash when logging out, or during gameplay?

**Comment by alcatrazEscapee** [comment] 2020-05-13 11:52
Duplicate of #840.

**Closed as completed by alcatrazEscapee** 2020-05-13 11:52 UTC
Labels: duplicate
