### ISSUE TITLE
Trees can sometimes generate on top of things they shouldn't

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2455] opened 2023-06-16 14:12 UTC
![2023-06-16_15 06 44](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/0405deba-56ac-4afc-a9c1-8be3d1564c66)

**Comment by alcatrazEscapee** [comment] 2023-06-16 14:37
Duplicate of #2454

**Closed as not planned by alcatrazEscapee** 2023-06-16 14:37 UTC
Labels: duplicate
