### ISSUE TITLE
Heating recipe not working as intended 

### ISSUE THREAD

**Issue by WitchkingsRu** [TerraFirmaCraft/TerraFirmaCraft#2818] opened 2024-11-06 18:21 UTC
Encountered a weird issue regarding heating recipes while working on my addon:
`{
    "type": "tfc:heating",
    "ingredient": {
        "item": "antiquelegacy:iron_niederbieber_helmet"
    },
    "result_fluid": {
        "fluid": "tfc:metal/bronze",
        "amount": 200
    },
    "result_item": {
        "stack": {
            "item": "tfc:metal/sheet/wrought_iron",
            "count": 1
        },
        "modifiers": [
            {
                "type": "tfc:add_heat",
                "temperature": 950
            }
        ]
    },
    "temperature": 950,
    "use_durability": true
}`
this recipe results in both bronze and wrought iron sheet be smelted immediately
as far as I tested it, modifiers of item stack doesn't matter, happens with "add_heat", "copy_heat" and without a modifier at all.
Also worth mentioning that all works as intended in charcoal forge, the issue affects only crucible smelting
https://youtu.be/cRhhN32KQco video depicting an issue

**Comment by alcatrazEscapee** [comment] 2024-11-06 18:37
Duplicate of #2819

**Closed as not planned by alcatrazEscapee** 2024-11-06 18:37 UTC
Labels: duplicate
