### ISSUE TITLE
Details regarding food preparation

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1221] opened 2020-05-07 23:43 UTC
Meat prepared in a forge doesnt stack with food prepared in a pitfire, also having different decay multipliers, so, for convenience, i think it should say "charcoal grilled" or "campfire cooked".
As for for other fooods, they also dont display "brined" os "pickled".
I havent tested but i assume salted meat also doesnt display "salted"
**Meta Info**
 - TFC Version: 1.0.11.140 (at time of request)

**Comment by alcatrazEscapee** [comment] 2020-05-07 23:50
It does, due to the different traits. There's a bug in said version with traits not getting displayed. Otherwise duplicate of #1217

**Closed as completed by alcatrazEscapee** 2020-05-07 23:50 UTC
Labels: duplicate
