### ISSUE TITLE
game crashes while using valkyrienskies

### ISSUE THREAD

**Issue by KingEnder999** [TerraFirmaCraft/TerraFirmaCraft#2836] opened 2024-11-27 14:58 UTC
whenever i try too enter the game while having VS installed the game just crashes and gives me this report (attachment)
[crash-2024-11-27_15.48.32-fml.txt](https://github.com/user-attachments/files/17936189/crash-2024-11-27_15.48.32-fml.txt)
does anyone know if theres a fix?
MC version:  1.20.1
Forge:           47.3.0
TFC version:  3.2.10

**Comment by alcatrazEscapee** [comment] 2024-11-27 16:27
Duplicate of https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2610

**Closed as completed by alcatrazEscapee** 2024-11-27 16:27 UTC
Labels: duplicate, Version: 1.20.x
