### ISSUE TITLE
Crash on startup [FORGE]

### ISSUE THREAD

**Issue by MaliciousLotus** [TerraFirmaCraft/TerraFirmaCraft#2704] opened 2024-05-13 07:50 UTC
I have a pretty large modpack, around 117ish mods or so. I've had this mod BEFORE I added things such as ModernFix, and FerriteCore, along with Eureka! Ships! for optimization and more fun. Not sure if those are the problem but here's the crash log. https://pastebin.com/rERYR2wr

**Comment by alcatrazEscapee** [comment] 2024-05-13 12:04
Duplicate of #2610

**Closed as not planned by alcatrazEscapee** 2024-05-13 12:04 UTC
Labels: duplicate
