### ISSUE TITLE
getting an unknown crash when adding TFC to my modpack

### ISSUE THREAD

**Issue by Nathan22211** [TerraFirmaCraft/TerraFirmaCraft#1427] opened 2020-06-21 14:45 UTC
**Describe the bug**
the latest curseforge version of TFC is crashing with the modlist from the pack linked
here's a log https://gist.github.com/Nathan22211/e1e736c0a3f5b284ee482ff8368ac00e

**To Reproduce**
Attention to detail is important!
1. install this pack in Twitch or MultiMC: https://www.curseforge.com/minecraft/modpacks/untitled-hardcore-pack
2. add TFC
3. load the game, it should crash before getting to the main menu

**Meta Info**
 - TFC Version: 1.5.2.152
 - all the mods in the latest version of this pack were included + TFC, (I'm the dev of this): https://www.curseforge.com/minecraft/modpacks/untitled-hardcore-pack, and on its own, the crash doesn't occur
 - Unfortunately, I don't know which mod(s) are causing it. an earlier log had a fatal for tinkers compendium but removing it didn't fix it

**Comment by alcatrazEscapee** [comment] 2020-06-21 15:00
Looks like a duplicate of #962 as `func_193986_ar` is `Minecraft#populateSearchTreeManager`.

**Closed as completed by alcatrazEscapee** 2020-06-21 15:00 UTC
Labels: bug, duplicate
