### ISSUE TITLE
Crash on River Block generation (1.17.1 Alpha 2.0.7)

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1830] opened 2021-12-11 23:46 UTC
The game consistently crashen on the version 1.17.1 using forge 37.1.0 when a riverblock is generated.

Here is the crash report:
[crash-2021-12-12_00.42.34-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/7697901/crash-2021-12-12_00.42.34-server.txt)

**Comment by alcatrazEscapee** [comment] 2021-12-12 00:08
Duplicate of #1829

**Closed as completed by alcatrazEscapee** 2021-12-12 00:08 UTC
Labels: duplicate
