### ISSUE TITLE
JEI integration for the charcoal pile.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1011] opened 2020-04-17 17:02 UTC
**Describe the request**
That's it really, a page in JEI when you search the recipes for charcoal that shows a mockup charcoal pile surrounded by soil would be useful.

**Comment by alcatrazEscapee** [comment] 2020-04-17 17:33
Duplicate of #588

**Closed as completed by alcatrazEscapee** 2020-04-17 17:33 UTC
Labels: duplicate, enhancement
