### ISSUE TITLE
Grass block texture is not rotated randomly

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2439] opened 2023-06-01 00:20 UTC
Vanilla's is. I'm not sure whether TFC's is intended to be or not.
![2023-05-31_12 53 32](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/185bb55e-1c97-43ad-8676-9ae1d04d3b17)

**Comment by alcatrazEscapee** [comment] 2023-06-01 00:33
Duplicate of #2434

**Closed as not planned by alcatrazEscapee** 2023-06-01 00:33 UTC

**Comment by muzikbike** [comment] 2023-08-29 15:01
This still happens in 2.2.29 despite #2434 being fixed.
