### ISSUE TITLE
Tomato Vinegar

### ISSUE THREAD

**Issue by HermitOwO** [TerraFirmaCraft/TerraFirmaCraft#1683] opened 2021-02-14 10:22 UTC
1. What problem or issue would this enhancement solve?
    Tomato is a fruit so you should be able to make vinegar with it.

2. Describe the feature itself - what would change, what would happen. In general more detail is good!
    Make vinegar with tomatoes, or better, just make tomato a fruit.

**Comment by alcatrazEscapee** [comment] 2021-02-14 14:50
Duplicate of #1288

**Closed as completed by alcatrazEscapee** 2021-02-14 14:50 UTC
Labels: duplicate

**Comment by ooooonnnnn** [comment] 2021-02-25 18:12
Vinegar can be made from tomatoes:
https://www.delightedcooking.com/what-is-tomato-vinegar.htm
And also, rice vinegar is a thing, although the procces of making it is different from the standard TFC fruit-vinegar-recipe, as it requires an artificial addition of sugar.
