### ISSUE TITLE
Bug - Landslide can occur INTO farmland blocks.

### ISSUE THREAD

**Issue by victhor003** [TerraFirmaCraft/TerraFirmaCraft#1626] opened 2020-11-14 14:21 UTC
**Bug:**
When a landslide occurs near farmlands, it's possible than the falling block appears over an adyacent farmland block, voiding the farmland block and replacing it with the falling block. Seems like the farmland isn't recognized as a solid block, since it doesn't have the full height of one.

**To Reproduce:**
1º: On one side have the farmland blocks.
2º: On the other side have a place where blocks can check to fall into once placed.
3º: Place the block between the two sides and it has a chance that i will choose to fall on the side of the farmland.

![bug3](https://user-images.githubusercontent.com/45216050/99149172-afb3b880-268c-11eb-8939-85c316cb75f9.gif)

**Meta Info**
 - TFC Version: 1.7.7.165

**Comment by alcatrazEscapee** [comment] 2020-11-14 15:42
Duplicate of #886

**Closed as completed by alcatrazEscapee** 2020-11-14 15:42 UTC
Labels: duplicate, working as intended
