### ISSUE TITLE
Invalid loom automation config option causing crash on world load

### ISSUE THREAD

**Issue by ammoore00** [TerraFirmaCraft/TerraFirmaCraft#2410] opened 2023-05-24 23:40 UTC
The new config option for whether or not to allow the loom to interact with automation generates in a malformed state, causing the game to crash when it loads a world.

The offending config:
```
[blocks.loom]

		[blocks.loom."will interact with in-world automation such as hoppers on a side-specific basis"]
			#If true, looms will interact with in-world automation such as hoppers on a side-specific basis.
			 = true
```

**Comment by alcatrazEscapee** [comment] 2023-05-24 23:58
Duplicate of #2409

**Closed as completed by alcatrazEscapee** 2023-05-24 23:58 UTC
Labels: duplicate
