### ISSUE TITLE
Minor Missing/Unusual Features

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#390] opened 2019-09-07 17:02 UTC
Using coal blocks to make forges like in TFC classic (I recommend adding piles of coal like charcoal does instead)

Barrel item cooling mechanics for hot items

Water bottles provide vanilla water to barrels, and can also be obtained by bottling from limewater/hotwater/fresh water sources, allowing vanilla water to be obtained, that's not too big an issue for mod compatibility but you definitely should not be able to get water from limewater source blocks...

**Comment by alcatrazEscapee** [comment] 2019-09-07 17:13
Separate issues should be in separate reports please. Also point 2. is a duplicate of #382.

**Closed by alcatrazEscapee** 2019-09-07 17:13 UTC
Labels: unconfirmed bug
