### ISSUE TITLE
Ability to right click barrel fluids into other barrels.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1377] opened 2020-06-01 11:23 UTC
Right clicking a sealed barrel in your hand onto another barrel should move it's fluid contents.
This is especially useful when a fluid is in a barrel you'd rather not waste, but can't even use.
Eg: Barrel with 100mb limewater in it, no recipe can use so little, no container can move so little.

**Comment by alcatrazEscapee** [comment] 2020-06-01 11:33
Duplicate of #493

**Closed as completed by alcatrazEscapee** 2020-06-01 11:33 UTC
Labels: duplicate
