### ISSUE TITLE
Water wheels don't power devices when rotating in a RH direction (negative speed)

### ISSUE THREAD

**Issue by Anthem1s** [TerraFirmaCraft/TerraFirmaCraft#2619] opened 2024-01-22 21:40 UTC
For example at x=15000, z=15000 there are animations of watermills and other stuff connected to them, but quern that is connected to it has endless spinning animation without any output. Quern connected to watermill near zero coords works properly.

**Comment by alcatrazEscapee** [comment] 2024-01-22 21:57
This sounds like it may be a duplicate of #2606 - can you provide additional information about what _specifically_ you did to observe a bug?

**Comment by Anthem1s** [comment] 2024-01-22 22:10
I placed waterwheels near zero and far away from it in the same world. Looking at wheel with the one probe mod shows it speed if it works properly. But far away from zero it doesn`t show rotating speed and quern doesnt work, while with windmill it`s fine

**Comment by LeoBeliik** [comment] 2024-01-26 02:57
I don't know if the same bug, but I[ have the same problem](https://discord.com/channels/432522930610765835/432527966266851339/1200263807273013289) except the waterwheel still doesn't work near 0, and I noticed that reverting to 3.1.4 fixes it.. I also noticed that a new world in 3.1.5 makes them just work again

**Comment by alcatrazEscapee** [comment] 2024-01-28 16:40
I cannot reproduce any of this behavior. Water wheels are working fine at both near 0, 0, and at 100k, 100k. This seems like some confusion with the aforementioned other Quern issue.

If there's another water wheel related issue here, I would need reproduction steps for a new world on the latest version. If you're having issues, or issues caused by an version bump, does break + replace or new world fix them.

**Comment by Anthem1s** [comment] 2024-01-28 17:40
So, I've created a new world, it's seed -6145986495716006771. At coordinates -3500, -2300, as well as 14300, 14900, querns that are connected to waterwheels do not grind items. But at -5200, -2500 quern connected to whaterwheel works fine. I'm not sure how, but coordinates affect if whaterwheel will work properly or not. The problem is with waterwheels, because querns powered with windmills work fine everywhere. It means that bug with quern may be only the consequence of this one.

**Comment by alcatrazEscapee** [comment] 2024-01-28 23:21
Alright, literally everything said here beyond "water wheels sometimes don't work" was bogus. Coordinates, world seed, save condition of the world don't matter, and it doesn't make any sense for them to matter. The rotation network is not saved as part of the world.

The specific bug here is water wheels, when placed and rotation in a right-hand direction, relative to the axis of the water wheel (positive direction), rotate with a negative speed, and some blocks don't handle that properly. In future, what _is_ helpful to diagnose issues with the rotation network is the **orientation** of the blocks in question, especially if changing said orientation makes a difference.

**Closed as completed** 2024-01-31 17:12 UTC
Labels: bug, fixed in dev, Version: 1.20.x
