### ISSUE TITLE
No ceramic products output in Pit Kiln in a 1.12.2 sponge forge server

### ISSUE THREAD

**Issue by GrayNekoBean** [TerraFirmaCraft/TerraFirmaCraft#1768] opened 2021-05-21 22:08 UTC
**Describe the bug**

When I tried to burn some ceramics in a Pit Kiln in a 1.12.2 Server, ceramics will disappear after the process finished, with only an empty "placed item" block left. I've tried to debug this problem several times and confirmed it is a conflict with sponge-forge 1.12.2-2838-7.3.0 (the same happens with the latest version 1.12.2-2838-7.3.1-RC4082). This bug happens only with sponge itself, even with no plugins loaded. 

**To Reproduce**

1. Start a 1.12.2 forge server 1.12.2-14.23.5.2854 installed with TerrafirmaCraft-MC1.12.2-1.7.18.176 and spongeforge-1.12.2-2838-7.3.0.
2. login to the server and make some ceramics with clay
3. put them into a Pit Kiln then burn them
4. wait for 8 game hours
5. got no product left after the process finished, only an empty "placed item" block.

**Meta Info**

 - Forge Version: 1.12.2-14.23.5.2854
 - TFC Version: MC1.12.2-1.7.18.176 
 - Spone Forge Version:  1.12.2-2838-7.3.0

**Comment by alcatrazEscapee** [comment] 2021-05-21 22:49
Duplicate of #664

**Closed as completed by alcatrazEscapee** 2021-05-21 22:49 UTC
Labels: duplicate
