### ISSUE TITLE
Gravity-affected blocks slide randomly across cleared grass blocks.

### ISSUE THREAD

**Issue by allenshoff** [TerraFirmaCraft/TerraFirmaCraft#736] opened 2020-01-11 16:52 UTC
When digging into a dirt hillside adjacent to grass blocks that had been de-turfed/dug down/cleared using the shovel (right click action), the falling dirt jumped across many of the cleared blocks, leaving un-dug blocks in its wake.

![dirt slide on turf removed grass](https://user-images.githubusercontent.com/28602240/72207553-1a81db00-344f-11ea-872d-ad074aa7c73a.png)

**To Reproduce**
This is reproducible with any gravity-affected block:  gravel, sand, dirt, cobblestone, etc.

1. Use shovel with right click to clear some grass below a hillside.
2. Trigger an avalanche or place a gravity-affected block where it will fall onto the cleared grass blocks.
3. Watch it dance around until it finally stops.

I theorize that because the cleared grass blocks are 1/8 below the level of adjacent blocks, the code that handles the relative height of the block is confused and causes it to jump all over the place. I've seen it slide on a level surface for 15-20 blocks; this screenshot was a relatively small area but did a good job showing the issue.

**Meta Info**
 - TFC Version: 0.27.5.105
 - CraftTweaker was included, but not in use. Bug occurs with or without it.

**Comment by alcatrazEscapee** [comment] 2020-01-11 17:00
Duplicate of #524

**Closed by alcatrazEscapee** 2020-01-11 17:00 UTC
Labels: unconfirmed bug
