### ISSUE TITLE
Game crash when trying to weld

### ISSUE THREAD

**Issue by ooooonnnnn** [TerraFirmaCraft/TerraFirmaCraft#1702] opened 2021-02-23 17:12 UTC
Game crashed when I tried to weld two copper ingots with a copper hammer on a granite anvil (with flax). 
Same error message as in the following crash report (welding without flax): https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/1698

"EntityPlayerSP cannot be cast to EntityPlayerMP
at TEAnvilTFC.attemptWelding, line 352"

**Comment by alcatrazEscapee** [comment] 2021-02-23 17:19
Duplicate of #1698

**Closed as completed by alcatrazEscapee** 2021-02-23 17:19 UTC
Labels: duplicate
