### ISSUE TITLE
Invisible floating top halves of plants can sometimes generate/be left behind

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2458] opened 2023-06-16 14:22 UTC
![2023-06-16_15 21 11](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/24129f92-2a56-4a76-b8c4-c463cf9ffc41)
![2023-06-16_15 21 35](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/0caa5218-1a0c-4c3e-9313-07db1deef769)
![2023-06-16_15 21 36](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/10e487cf-0218-4b08-b575-c09c2204b11d)

**Comment by alcatrazEscapee** [comment] 2023-06-16 14:38
Duplicate of #2454

**Closed as not planned by alcatrazEscapee** 2023-06-16 14:38 UTC
Labels: duplicate
