### ISSUE TITLE
Game crashes when Leaves Block is placed

### ISSUE THREAD

**Issue by SheReyy** [TerraFirmaCraft/TerraFirmaCraft#2814] opened 2024-11-01 18:58 UTC
TFC: 3.2.9
Forge: 47.3.0

I was in a superflat world. I placed a Maple Leaves block, then the game crashed. I haven't tasted with other leaves.

[Here](https://gist.github.com/SheReyy/635b35958d8714c4f9c84fd738172747)'s the crash log

**Comment by alcatrazEscapee** [comment] 2024-11-01 23:47
Duplicate of #2812

**Closed as not planned by alcatrazEscapee** 2024-11-01 23:47 UTC
