### ISSUE TITLE
drinking milk makes saturation NaN

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2343] opened 2023-03-22 23:27 UTC
![2023-03-22_17 15 14](https://user-images.githubusercontent.com/58122689/227061103-eda3698c-5fb1-4605-8c13-8d3a6df3c776.png)
![2023-03-22_17 15 22](https://user-images.githubusercontent.com/58122689/227061107-1faaa8b3-5ce9-4d91-8747-000bb8f58d64.png)
![2023-03-22_17 26 01](https://user-images.githubusercontent.com/58122689/227061109-0ce5ee30-8f23-4993-85a6-a2a543aa2ffd.png)

**Comment by alcatrazEscapee** [comment] 2023-03-22 23:41
Duplicate of #2344

**Closed as completed by alcatrazEscapee** 2023-03-22 23:41 UTC
Labels: duplicate
