### ISSUE TITLE
Grass paths sometimes have blocks above fall into it

### ISSUE THREAD

**Issue by KemanDragon** [TerraFirmaCraft/TerraFirmaCraft#938] opened 2020-04-03 02:51 UTC
**Describe the bug**
Make sure to include:
1. Grass paths should not revert to dirt
2. Sometimes, on nearby block updates, paths on a "step" above will turn back into dirt and fall into path blocks below, which destroys the block as intended.
3. This wasn't a crash.
4. Screenshot included. The gap visible was a path block before, which reverted to dirt and then fell into the space where there is now dirt on the next level down once a block update occurred nearby
![2020-04-02_22 34 14](https://user-images.githubusercontent.com/17956289/78318332-7893fb00-7532-11ea-9cd0-28a993ababd7.png)

**To Reproduce**
1. Make path blocks in a slope setup
2. Then wait for or force a nearby block update (as when making more paths or when grass grows onto dirt blocks)

**Meta Info**
 - TFC Version: 0.30.3.124
 - Mods included are BiblioCraft, Chisels and Bits, CraftTweaker, Creative Core, Connected Textures Mod, Dynamit Trees, Dynamic Trees TFC, HYWLA, Immersive Engineering, Inventory Tweaks, JEI, JourneyMap, Little Tiles, MC Multipart, TFC Metallum, TFCTech, and Water Flasks. I was able to recreate the bug without the mods, however.

**Comment by alcatrazEscapee** [comment] 2020-04-27 03:10
Duplicate of #564, may revisit special casing this at some point

**Closed as completed by alcatrazEscapee** 2020-04-27 03:10 UTC
Labels: duplicate, working as intended
