### ISSUE TITLE
Barrels with any liquid when sealed display "preserving in vinegar"

### ISSUE THREAD

**Issue by M8-u** [TerraFirmaCraft/TerraFirmaCraft#1291] opened 2020-05-18 21:51 UTC
![2020-05-18_14 35 10](https://user-images.githubusercontent.com/53875064/82263024-0d5e8680-9930-11ea-818c-b32083c2f73d.png)

Bug occurs on TFC version 1.2.0.143

**Comment by alcatrazEscapee** [comment] 2020-05-18 22:05
Duplicate of #1286

**Closed as completed by alcatrazEscapee** 2020-05-18 22:05 UTC
Labels: duplicate
