### ISSUE TITLE
Crash after death, can't load world

### ISSUE THREAD

**Issue by DubroNoDumbo** [TerraFirmaCraft/TerraFirmaCraft#2734] opened 2024-06-24 18:36 UTC
`---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-24 20:33:33
Description: Unexpected error

java.lang.IllegalStateException: Missing class net.dries007.tfc.common.capabilities.player.PlayerData
	at net.dries007.tfc.common.capabilities.player.PlayerData.lambda$get$0(PlayerData.java:38) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[forge-1.20.1-47.2.17-universal.jar%23185!/:?] {re:classloading}
	at net.dries007.tfc.common.capabilities.player.PlayerData.get(PlayerData.java:38) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.dries007.tfc.common.recipes.ChiselRecipe.computeResult(ChiselRecipe.java:56) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.dries007.tfc.client.ClientForgeEventHandler.onHighlightBlockEvent(ClientForgeEventHandler.java:498) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawHighlight(ForgeHooksClient.java:274) ~[forge-1.20.1-47.2.17-universal.jar%23185!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1328) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.LevelRendererMixin,pl:mixin:APP:tfc.mixins.json:client.accessor.LevelRendererAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.17.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	TerraFirmaCraft (tfc), Version: 3.2.4
		Issue tracker URL: https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues
		at TRANSFORMER/tfc@3.2.4/net.dries007.tfc.common.capabilities.player.PlayerData.lambda$get$0(PlayerData.java:38)
Stacktrace:
	at net.dries007.tfc.common.capabilities.player.PlayerData.lambda$get$0(PlayerData.java:38) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[forge-1.20.1-47.2.17-universal.jar%23185!/:?] {re:classloading}
	at net.dries007.tfc.common.capabilities.player.PlayerData.get(PlayerData.java:38) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.dries007.tfc.common.recipes.ChiselRecipe.computeResult(ChiselRecipe.java:56) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.dries007.tfc.client.ClientForgeEventHandler.onHighlightBlockEvent(ClientForgeEventHandler.java:498) ~[TerraFirmaCraft-Forge-1.20.1-3.2.4.jar%23178!/:3.2.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2397!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawHighlight(ForgeHooksClient.java:274) ~[forge-1.20.1-47.2.17-universal.jar%23185!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1328) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.LevelRendererMixin,pl:mixin:APP:tfc.mixins.json:client.accessor.LevelRendererAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 529, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (320,78,3440), Section: (at 0,14,0 in 20,4,215; chunk contains blocks 320,-64,3440 to 335,319,3455), Region: (0,6; contains chunks 0,192 to 31,223, blocks 0,-64,3072 to 511,319,3583)
	Level time: 750996 game time, 750831 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:tfc.mixins.json:client.ClientLevelMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.17.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, Firmalife-1.20.1-2.1.5.jar:overload

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.11, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 805752120 bytes (768 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 PRO 5750G with Radeon Graphics     
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=31.0.21912.14
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 15125.60
	Virtual memory used (MB): 10815.29
	Swap memory total (MB): 896.00
	Swap memory used (MB): 1.64
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon(TM) Graphics GL version 4.6.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: it_it
	CPU: 16x AMD Ryzen 7 PRO 5750G with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['FnoRky_'/14, l='ServerLevel[Koduky 2.0]', x=-1773.42, y=60.19, z=3454.31, removed=KILLED]]
	Data Packs: vanilla, mod:jade (incompatible), mod:ferritecore (incompatible), mod:jei, mod:alekiehm, mod:skinlayers3d, mod:forge, mod:tfc, mod:firmalife (incompatible), mod:firmaciv (incompatible), mod:tfcambiental, mod:curios (incompatible), mod:sound_physics_remastered (incompatible), mod:patchouli (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Jade-1.20.1-forge-11.9.3.jar                      |Jade                          |jade                          |11.9.3+forge        |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		jei-1.20.1-forge-15.3.0.8.jar                     |Just Enough Items             |jei                           |15.3.0.8            |DONE      |Manifest: NOSIGNATURE
		alekiEHM-FORGE-1.0.3-1.20.1.jar                   |aleki's Easy Held Models      |alekiehm                      |1.0.3-1.20.1        |DONE      |Manifest: NOSIGNATURE
		skinlayers3d-forge-1.6.6-mc1.20.1.jar             |3d-Skin-Layers                |skinlayers3d                  |1.6.6               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.17-universal.jar                |Forge                         |forge                         |47.2.17             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TerraFirmaCraft-Forge-1.20.1-3.2.4.jar            |TerraFirmaCraft               |tfc                           |3.2.4               |DONE      |Manifest: NOSIGNATURE
		Firmalife-1.20.1-2.1.5.jar                        |Firmalife                     |firmalife                     |2.1.5               |DONE      |Manifest: NOSIGNATURE
		FirmaCivilization-0.2.10-alpha-1.20.1.jar         |Firma: Civilization           |firmaciv                      |0.2.10-alpha-1.20.1 |DONE      |Manifest: NOSIGNATURE
		tfcambiental-1.20.1-3.3.0.jar                     |TFC Ambiental                 |tfcambiental                  |1.20.1-3.3.0        |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.9.1+1.20.1.jar                     |Curios API                    |curios                        |5.9.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.1-1.4.2.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.4.2        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b6a316f5-ffae-4562-a3e4-8b34475a43a4
	FML: 47.2
	Forge: net.minecraftforge:47.2.17`

this is the crash report, I can't figure out what to do

**Comment by alcatrazEscapee** [comment] 2024-06-24 19:01
How did you reproduce this? Does it always happen in a specific world, if so can you send that world? Does it happen with only TFC and Patchouli installed?

**Comment by DubroNoDumbo** [comment] 2024-06-25 11:30
I couldn't reproduce this error, but creating a new instance with only TFC and Patchouli and loading the same world it didn't crash.
I tried to disable each mod at the time and see if it keep crashing, in the end disabling both JADE and JEI it fix the error every time,  only if both are disabled.

**Comment by alcatrazEscapee** [comment] 2024-06-25 12:27
Can you send the exact steps you use to reproduce this? With Jade + JEI + TFC + Patchouli, what causes the crash, and does it require your existing world or can you reproduce this with a new world with those mods?

**Comment by alcatrazEscapee** [comment] 2024-07-25 18:03
Closing as unreproducible given no further feedback.

**Closed as not planned by alcatrazEscapee** 2024-07-25 18:03 UTC
Labels: unconfirmed bug, Version: 1.20.x

**Comment by Starrysparklez** [comment] 2025-09-15 18:36
Hello! Have the same issue, but while playing on the server. The problem was reproduced on the multiplayer server with the TerraFirmaGreg-Modern modpack. I was flying on the quadrocopter from the Immersive Aircraft and got striked by a lightning bolt. Then I died and the game has crashed.

Crash report is here: https://gist.github.com/Starrysparklez/cb4b71a4f0260824121357fcd610b565

Anyway, possible way to fix this is to set the `doImmediateRespawn` game rule to `true`.
