### ISSUE TITLE
Players in Peaceful mode can get thirsty

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#142] opened 2019-06-29 17:01 UTC
Since peaceful mode stops players from getting hungry, I'd assume it would be meant to stop thirst as well.

**Comment by alcatrazEscapee** [comment] 2019-06-29 17:03
Fixed in https://github.com/alcatrazEscapee/TerraFirmaCraft/tree/damage-food-v2

**Comment by alcatrazEscapee** [comment] 2019-06-29 17:06
Duplicate of #108

**Closed by alcatrazEscapee** 2019-06-29 17:06 UTC
Labels: bug, duplicate
