### ISSUE TITLE
Fruit tree growth stunted when adjacent to a rock or stick

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1385] opened 2020-06-03 17:33 UTC
See image, fruit trees only grow on three sides and don't go up any further than this when a rock or stick is adjacent on the ground.

![2020-06-03_17 41 56](https://user-images.githubusercontent.com/58256171/83668991-c2e43780-a5c8-11ea-881c-48c7b7e355b0.png)

**Meta Info**
 - TFC Version: 0.X.X.146 on test server

**Comment by DisasterMoo** [comment] 2020-06-04 13:20
Duplicate of #924

**Closed as completed by DisasterMoo** 2020-06-04 13:20 UTC
Labels: working as intended
