### ISSUE TITLE
Land plants can incorrectly generate in water bodies

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2456] opened 2023-06-16 14:19 UTC
![2023-06-16_15 17 28](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/e6bb1787-c2c2-4005-985f-f84b118175d8)

**Comment by alcatrazEscapee** [comment] 2023-06-16 14:38
Duplicate of #2454

**Closed as not planned by alcatrazEscapee** 2023-06-16 14:38 UTC
Labels: duplicate
