### ISSUE TITLE
Small Vessel continuos brilliant white on cruscible even with forge turned off

### ISSUE THREAD

**Issue by marcelopio** [TerraFirmaCraft/TerraFirmaCraft#1101] opened 2020-04-25 21:04 UTC
**Describe the bug**
1. What did you expect to happen?
Temperature of small vessel to decrease while on cruscible
2. What actually happened instead (i.e. what was the bug)
Temperature keeps being brilliant white, even with forge fully turned off

In the screenshot attached the small vessel is empty, but the behaviour is the same with it full

**To Reproduce**
1. Put Small Vessel on cruscible
2. Heat the forge
3. Remove the forge fuel

**Meta Info**
 - TFC Version: 1.0.2.129
 - Were any other mods included? Can you reproduce it without these other mods?
Yes. Yes.
![2020-04-25_18 00 36](https://user-images.githubusercontent.com/9059039/80290883-0e303e00-871f-11ea-8005-501ce52c9007.png)

**Comment by alcatrazEscapee** [comment] 2020-05-14 22:06
Can't reproduce at all. I'm going to assume this was fixed in the last round of synchronization standardization. If not, we can revisit.

**Comment by DisasterMoo** [comment] 2020-05-17 01:16
Closing since it seems to be fixed. If anyone have this bug again, feel free to reopen / tell us in discord.

**Closed as completed by DisasterMoo** 2020-05-17 01:16 UTC
Labels: bug, fixed in dev
