### ISSUE TITLE
Conflict between 3 mods. 

### ISSUE THREAD

**Issue by Xelbayria** [TerraFirmaCraft/TerraFirmaCraft#1218] opened 2020-05-07 19:46 UTC
Minecraft Version: 1.12.2
Forge Version:  forge-14.23.5.2854
TFC Version: TerraFirmaCraft-MC1.12.2-1.0.10.140.jar

Other mods: 
ForgeCraft-1.6.51.jar
PrimalCore-1.12.2-0.6.105.jar

Crash Report: 
https://pastebin.com/QxVLyE7T

These mods are having a conflict with each other. But TFC is working without them, there' s no problem at all. Without TFC, these mods had no problem as well. 

I feared that there may not enough information in the Crash report since I already reported this to the author of these 2 mods. I hope you know what's going on. If you need any more information, just let me know and I'll do my best to get more.

**Comment by alcatrazEscapee** [comment] 2020-05-07 21:21
Duplicate of #381, see resolution there.

**Closed as completed by alcatrazEscapee** 2020-05-07 21:21 UTC
Labels: duplicate

**Comment by Xelbayria** [comment] 2020-05-07 21:42
Thank you. that solved my issue.
