### ISSUE TITLE
Snow slows even while you are jumping over it, clearly not touching it, as long as your feet are in the same block as the snow is

### ISSUE THREAD

**Issue by lumagatto** [TerraFirmaCraft/TerraFirmaCraft#2131] opened 2022-09-18 13:23 UTC
How should it work:
Slow down should be applied if feet are at or below the height of the snow (vanilla or tfc snow pile) in the block (in practice, if you are visibly touching the snow).

**Comment by alcatrazEscapee** [comment] 2022-09-28 15:44
Easy reproduction: place a line of snow and a line of slabs. Walk where the player is clearly on top of the slabs (by height) and not touching the snow, but hanging over the snow. Observe the player is slowed.

- Notably, vanilla also plays the sounds for walking over snow - clearly vanilla's detection for what block the player is walking on is interesting, in that case.
- Since we just use the snow blocks' `speedFactor` rather than `entityInside`, this may be intended behavior in vanilla - the former only being used for full blocks, based on the walking on check aforementioned via the sound.

**Comment by alcatrazEscapee** [comment] 2022-10-18 02:11
This looks to actually be the case for vanilla, and is a case of [MC-182442](https://bugs.mojang.com/browse/MC-182442). While we still may attempt to fix this, I'll closing this issue as it's not our issue.

**Closed as completed by alcatrazEscapee** 2022-10-18 02:11 UTC
Labels: bug, mojang pls, Version: 1.18.x
