### ISSUE TITLE
Placing log pile in invalid location (i.e. no solid block below) doesn't place the block but still consumes an item

### ISSUE THREAD

**Issue by Enzo12091209** [TerraFirmaCraft/TerraFirmaCraft#92] opened 2019-06-20 22:55 UTC
If you try to create a log pile in the air, the logs disappears from your Inventory

**Comment by alcatrazEscapee** [comment] 2019-06-20 22:58
Possible duplicate of #66?

**Closed** 2019-06-21 00:00 UTC
Labels: bug
