### ISSUE TITLE
Crash when removing items from pit kiln, world will not load without crash.

### ISSUE THREAD

**Issue by Firecracker74** [TerraFirmaCraft/TerraFirmaCraft#435] opened 2019-09-18 11:56 UTC
When removing items from pit kiln (one clay vessel of 1000+ units of copper and one vessel of ~300 units of bismuth bronze), game freezes for a few seconds then crashes. After crash, world cannot be reopened without crashing a few seconds later.

Crash report 1:
[crash-2019-09-18_07.47.56-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3626221/crash-2019-09-18_07.47.56-server.txt)

Crash after attempting to open world again:
[crash-2019-09-18_07.49.20-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3626224/crash-2019-09-18_07.49.20-server.txt)

Latest TFC build, only additional mods are jei, hwyla, journeymap, RTG, and craftstudioAPI.

**Comment by alcatrazEscapee** [comment] 2019-09-18 13:31
Seems to be a duplicate of #426. It seems to be an issue with ceramic vessels created in older versions. There may be a proper way to resolve this but for now the fix is to create a new world.

**Closed by alcatrazEscapee** 2019-09-18 13:31 UTC
Labels: unconfirmed bug
