### ISSUE TITLE
Soil color changes when placing a plant inside of a flower pot

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2437] opened 2023-06-01 00:16 UTC
TFC flower pots use the loam dirt texture on the inside, but the empty pot uses vanilla's dirt texture. This would be an easy fix by just having TFC overwrite vanilla's pot model with a custom model, but I'm not sure how desirable this is for the sake of mod compatibility.
![2023-06-01_01 14 53](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/a4fb7cf8-df35-4076-8d05-5416bbc1363c)
![2023-06-01_01 14 54](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/ca78a6e0-a321-422a-a83d-bb70814c2a28)

**Comment by alcatrazEscapee** [comment] 2023-06-01 00:33
Duplicate of #2434

**Closed as not planned by alcatrazEscapee** 2023-06-01 00:33 UTC
