### ISSUE TITLE
Exception generating new chunk: Cannot load from int array because "this.surfaceHeights" is null

### ISSUE THREAD

**Issue by mosharky** [TerraFirmaCraft/TerraFirmaCraft#2766] opened 2024-08-17 00:45 UTC
I get a CTD when trying to generate new chunks. I'm running TFC with a bunch of Fabric mods using Connector but I'm not sure if that's related to the crash

[latest.log](https://mclo.gs/Lu76sa7)
[crash report](https://mclo.gs/Tqi7mab)

**Comment by alcatrazEscapee** [comment] 2024-08-17 15:29
You have corrupted chunks, caused by something mucking with how chunk generation works. Previously this was caused by Distant Horizons' distant generation (see #2661). I'm assuming this is the same issue, or the same issue caused by a different mod.

**Comment by mosharky** [comment] 2024-08-17 15:33
I think it might've been caused by [C3ME](https://modrinth.com/mod/connectored-c2me-(c2me-fork-for-connector)). It was installed when the world generated and then removed prior to generating that log and crash. 

I removed it since I figured it was causing the crashes but they persisted even without the mod in that world, so yeah I guess it would mean something is corrupted

**Comment by alcatrazEscapee** [comment] 2024-10-31 16:19
Closing as unreproducible.

**Closed as completed by alcatrazEscapee** 2024-10-31 16:19 UTC
Labels: mod conflict, Version: 1.20.x
