### ISSUE TITLE
Goldpanning not always updating texture

### ISSUE THREAD

**Issue by Azaysol** [TerraFirmaCraft/TerraFirmaCraft#1467] opened 2020-07-14 06:24 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen? when gold panning sometimes the item texture wont update to show that you have completed panning
2. What actually happened instead (i.e. what was the bug) texture does not always update

**Meta Info**
 - TFC Version: x.153

**Comment by eerussianguy** [comment] 2020-07-14 16:45
#885

**Comment by alcatrazEscapee** [comment] 2020-07-14 21:10
Duplicate of #885

**Closed as completed by alcatrazEscapee** 2020-07-14 21:10 UTC
Labels: duplicate
