### ISSUE TITLE
Glitch interaction between TFC and Paths slowing the player

### ISSUE THREAD

**Issue by KittenRaee** [TerraFirmaCraft/TerraFirmaCraft#1645] opened 2020-12-04 18:36 UTC
**Describe the bug**

When using Paths together with TFC, both mods modify players movement speed. When player gets low on food and water, enough for TFC to apply penalties while on blocks that modify speed, then filling up on needs while on different blocks brings player up to "unmodified" speed, changing player's permanently: Eg. when player is standing on block that provides 133% movement speed, after filling up needs it causes player movement speed to go back only to 100%, but Paths treats that 100% as if it was 133%, making new baseline 75% speed when stepped off paths that modify movement speed. This glitch compounds and causes gradual and permanent slowing of player movement speed, that can only be fixed by dying.

**To Reproduce**

1. Stand on surface that increases movement speed: shovelled Grass Paths are quick example; Brick Blocks or Diamond Blocks have higher movement speed associated with them so glitch onsets faster while standing on them.
1. Wait to be hungry and thirst to the point movement speed penalty is applied
2. Eat and drink while still on aforementioned blocks.
3. Glitch happens gradually while repeating previous steps, change in FoV is a good indicator how far it is progressing

**Meta Info**

Required mods:
 - TFC version: 1.7.9.167
 - [Paths](https://www.curseforge.com/minecraft/mc-mods/paths) version 1.6.1 ([GitHub Repo](https://github.com/Tfarcenim/paths))

**Comment by alcatrazEscapee** [comment] 2020-12-04 18:51
Initial thoughts:

> Wait to be hungry and thirst to the point movement speed penalty is applied

We give the player the slowness potion effect. If this causes an issue I'd fully expect it to also be reproducible by just drinking a slowness potion / drinking milk to remove. In which case, there's very little we can do if Paths doesn't handle that correctly (i.e. not correctly compensating for movement modifiers. If there are other cases (because I know of other TFC blocks which affect player movement speed, i.e. thatch) those are probably a separate issue.

**Comment by alcatrazEscapee** [comment] 2022-07-20 21:08
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.

**Closed as completed by alcatrazEscapee** 2022-07-20 21:08 UTC
Labels: needs update, unconfirmed bug, mod conflict, Version: 1.12.x
