### ISSUE TITLE
Z-fighting on adjacent athyrium ferns

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2435] opened 2023-06-01 00:11 UTC
![2023-05-31_22 23 45](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/d4bbe0db-f1b9-4bc8-961f-b7768ee66f30)

**Comment by alcatrazEscapee** [comment] 2023-06-01 00:33
Duplicate of #2434

**Closed as not planned by alcatrazEscapee** 2023-06-01 00:33 UTC

**Comment by muzikbike** [comment] 2023-08-29 15:00
This still happens in 2.2.29 despite #2434 being fixed.
