### ISSUE TITLE
Shearing sheep with shears gives bad wool

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#616] opened 2019-12-03 10:42 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
I expected to get wool when shearing a sheep.
2. What actually happened instead (i.e. what was the bug)
I got a 'wool' item without texture, that I couldn't craft with a spindle to get Wool Yarn. 

**To Reproduce**
Attention to detail is important!
1. Do '...'
Shear sheep with Shears.
![2019-12-03_00 00 48](https://user-images.githubusercontent.com/58256171/70044105-96b81180-15b9-11ea-9508-ad5b515d09f1.png)

**Meta Info**
 - TFC Version: 0.X.X.98, on the test server.

**Comment by Abdyman** [comment] 2019-12-04 09:06
pretty sure this is the same issue is #526

**Comment by alcatrazEscapee** [comment] 2019-12-04 14:30
Duplicate of #526

**Closed by alcatrazEscapee** 2019-12-04 14:30 UTC
Labels: unconfirmed bug
