### ISSUE TITLE
Baby pigs glitch through stone walls when level is loaded

### ISSUE THREAD

**Issue by kingkoronov** [TerraFirmaCraft/TerraFirmaCraft#1380] opened 2020-06-01 17:27 UTC
**Describe the bug**
1. What did you expect to happen?
All animals can be reliably contained in stone walls.
2. What actually happened instead (i.e. what was the bug)
I have a pen that contains a litter of baby pigs. When I log out of my singleplayer world and log back in, the ones close to the wall are inside the blocks and can walk out of the pen.

**To Reproduce**
Attention to detail is important!
1. Create a singleplayer world
2. Build a small pen out of stone walls.
3. Lead a familiarized male and female pig into the pen.
4. Breed them.
5. When there are baby pigs, log out of the world and log back in. Some of the baby pigs may now be able to walk out.

**Meta Info**
 - TFC Version: 1.3.2.147
 - Other mods: Xaero's minimap, Xaero's world map, JEI, Waila, Hardcore darkness

**Comment by DisasterMoo** [comment] 2020-06-01 18:31
Known mojang bug, duplicate of #1229

**Closed as completed by DisasterMoo** 2020-06-01 18:31 UTC
Labels: duplicate
