### ISSUE TITLE
Adding custom data for a food crashes because it adds the food twice to the Creative Mode tab.

### ISSUE THREAD

**Issue by CKenJa** [TerraFirmaCraft/TerraFirmaCraft#2655] opened 2024-03-03 10:44 UTC
When adding a custom JSON file for a food item not included in TFC to a data pack, the game crashes because the same food item is added twice to the Creative Mode tab.

# Steps to Reproduce:

Add the custom JSON file for the food item not included in TFC to a data pack.
Launch the game and enter Creative Mode.
Notice that the same food item appears twice in the Creative Mode tab.
Attempting to select the item results in a crash with the message: java.lang.IllegalStateException: Accidentally adding the same item stack twice [Sweet Roll] to a Creative Mode Tab: Search Items.

# Expected Behavior:
Adding the custom JSON file for the food item to a data pack should only add the item once to the Creative Mode tab, without causing a crash.

# Current Behavior:
Adding the custom JSON file for the food item to a data pack results in the item being added twice to the Creative Mode tab, causing a crash.

# Related Code or Files:
Attached is the custom JSON file for the food item that causes the crash:
[sweet_roll.json](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/14472590/sweet_roll.json)
[crash-2024-03-03_18.11.45-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/14472593/crash-2024-03-03_18.11.45-client.txt)

**Comment by alcatrazEscapee** [comment] 2024-03-03 15:03
This does not make sense. I've seen this report before but _only_ with reference to create's "sweet roll". TFC does not do anything to add food items to creative tabs, nor does the presence of food affect creative tabs in any way. In addition we've had plenty of cases of adding food for mods with no conflicts. This seems almost certainly like a conflict either create or a forge interaction.

---

Moreover, I cannot reproduce this crash. With the listed version of Create + the attached file, it works fine.

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35673674/f51164dc-94c6-465c-91a2-048fd828d3d1)

**Comment by CKenJa** [comment] 2024-03-05 08:55
food with data added in JSON showed up in the Creative Inventory search field two at a time, but only one at a time for those that did not.
It is unclear which mod conflicts are the cause; in addition to Create and TFC, at least two more mods seem to be involved.
![2024-03-05_10 21 19](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/41111170/99799961-e840-4484-a8c1-4fdf18dcdade)

**Comment by alcatrazEscapee** [comment] 2024-10-31 16:18
Closing as unreproducible.

**Closed as completed by alcatrazEscapee** 2024-10-31 16:18 UTC
Labels: mod conflict, Version: 1.20.x
