### ISSUE TITLE
Loss of oil in lamp when attempting to stack

### ISSUE THREAD

**Issue by Hawk777** [TerraFirmaCraft/TerraFirmaCraft#1638] opened 2020-11-28 20:41 UTC
**Describe the bug**
It appears that lamps with oil in them should not be stackable. However, when repeatedly trying to stack two oil-filled lamps of the same metal, occasionally it works and results in a stack of two empty lamps, thus destroying the oil.

**To Reproduce**
1. Create two empty lamps made of the same metal.
2. Fill both lamps in a barrel and stash them in your inventory.
3. Open your inventory.
4. Click on one lamp to pick it up into your cursor.
5. Click on the second lamp, as if trying to stack them, which should swap them instead as they should be unstackable.

Repeating step 5, or even steps 3 through 5, a few times may be necessary. I also once or twice saw the oil teleport itself back into the barrel from which I filled the lamps, but that does not usually happen.

Might be related to #1513, but that is listed as fixed in a commit that was included in 167 (indeed 162 and above). That ticket also mentions dedicated servers, but I’m playing singleplayer.

**Meta Info**
 - TFC Version: 1.7.9.167
 - Were any other mods included? No other mods

**Comment by Rongmario** [comment] 2020-11-29 03:30
Reproducible. 

Although, it seems to be a simple sync issue, as if you split the stack apart again, you can see the fluid is still retained, even when you place it down whilst holding it as the stack.

**Comment by alcatrazEscapee** [comment] 2022-07-20 21:08
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.

**Closed as completed by alcatrazEscapee** 2022-07-20 21:08 UTC
Labels: bug, Version: 1.12.x
