### ISSUE TITLE
Saddled horse disappeared until relog

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#984] opened 2020-04-13 14:01 UTC
My saddled horse disappeared when I dismounted. Atlanta0 had had this a few times and suggested relogging, which caused the horse to become visible again.

Intermittent, haven't had a second occurrence yet.

Not had this happen before in all the hours I played on previous map and versions on same server, same optifine version.

**Meta Info**
 - TFC Version: 0.X.X.126 on test server
- Optifine

**Comment by Azaysol** [comment] 2020-04-13 23:53
can you try updating to version 127 and let them know if this happens again. a lot of animal updates and fixes went out for it

**Comment by p0kes** [comment] 2020-04-16 14:00
Still happens intermittently on 128

**Comment by p0kes** [comment] 2020-05-14 17:31
Still happens sometimes on .142
Confirmed not Optifine as I'm no longer using it.

**Comment by DisasterMoo** [comment] 2020-05-14 22:06
Since it's hard to reproduce, it's also hard to fix. If you figure out a step by step reproduction method, either by world seed, your world save or anything different than luck please send it to me, otherwise i can't find what is causing it.

**Comment by DisasterMoo** [comment] 2020-05-15 21:46
Found out this: https://bugs.mojang.com/browse/MC-105170. Seems that it also occurs in 1.14, so, since this is a bug in MC, unless you can find a step reproduction, i'm calling this unfixable in 1.12.

**Comment by alcatrazEscapee** [comment] 2020-05-15 21:58
Somewhat more accurately, <https://bugs.mojang.com/browse/MC-101247>, which is the non-duplicate issue, stating it is resolved in 1.15.

**Closed as completed by alcatrazEscapee** 2020-05-15 21:58 UTC
Labels: bug, wont fix, mojang pls
