### ISSUE TITLE
Smithing an item into a valid input item doesn't select single recipe plan.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1393] opened 2020-06-05 15:28 UTC
Have item in anvil.
Smith it into something else.
That new item is also a valid input for only one output option (like how the blooms detect refined blooms as the only valid recipe and select it's plan)
The plan doesn't auto select.

**Comment by alcatrazEscapee** [comment] 2020-06-05 15:35
Duplicate of #1314

**Closed as completed by alcatrazEscapee** 2020-06-05 15:35 UTC
Labels: duplicate
