### ISSUE TITLE
Time of day is frozen (1.18.2)

### ISSUE THREAD

**Issue by BOUNSround** [TerraFirmaCraft/TerraFirmaCraft#2590] opened 2023-12-23 16:54 UTC
So, I was playing solo in my survival world and everything was fine until yesterday, where for some reason, my time decided to freeze. I noticed the night was taking forever to end and checked on the time, and there it was, frozen. I tried to use time commands on creative mode, but nothing happens. I also checked if this bug happened with other worlds and their clocks/time work just as intended. 

Here is a print of the time, it won't leave 7:00 AM no matter what I do

![imagem_2023-12-23_135358985](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/154693492/7d6fb06c-ca56-456a-bb1c-0e987f63d1a7)

**Comment by alcatrazEscapee** [comment] 2023-12-23 16:56
Duplicate of #2562

**Closed as completed by alcatrazEscapee** 2023-12-23 16:56 UTC
Labels: duplicate
