### ISSUE TITLE
Summoned or spawned animals have a 50% chance of being old

### ISSUE THREAD

**Issue by eerussianguy** [TerraFirmaCraft/TerraFirmaCraft#1037] opened 2020-04-19 14:49 UTC
version 131. Not sure if this is intended but its a little strange that spawn eggs would create new animals that are already too old to breed.

**Comment by DisasterMoo** [comment] 2020-04-19 18:29
Not a bug, but also shouldn't be 50%. Random spawns (including spawn eggs, but not on chunk generation since there is another spawn logic there to accommodate group of animals) will always be adults, but has a random age from 1 day being adult and full old, which would imply that the chance of getting an old animal should be very slim. Anyway, i will take a look.

**Comment by DisasterMoo** [comment] 2020-05-13 18:14
Should've been fixed by build 142.

**Closed as completed by DisasterMoo** 2020-05-13 18:14 UTC
Labels: unconfirmed bug
