### ISSUE TITLE
Config for Barrel temp.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1084] opened 2020-04-23 02:52 UTC
TFC 133
Add a config for the max temp a barrel can hold.

**Comment by alcatrazEscapee** [comment] 2020-04-23 03:51
Duplicate of #942, no? I think a proper whitelist would be better served than just a temperature based config option.

**Closed as completed by alcatrazEscapee** 2020-04-23 03:51 UTC
Labels: duplicate, enhancement
