### ISSUE TITLE
Barrels glitching on latest version

### ISSUE THREAD

**Issue by vasilDerilov** [TerraFirmaCraft/TerraFirmaCraft#1191] opened 2020-05-05 21:51 UTC
The bug occurs when I try to seal a barrel
Instead of the unsealing correctly it stays sealed and won't unseal visually, in reality, it gets unsealed because I can place items inside somehow.

**To Reproduce**
Just try to seal a barrel and then unseal it, my issue was with a Douglas fir barrel

**Meta Info**
 - TFC Version: 1.0.11.140
 - Were any other mods included? Journey map, Waila, NEI, JEI, OptiFine, and their dependencies 
 - I don't think the mods had any role in the bug

**Comment by alcatrazEscapee** [comment] 2020-05-05 21:55
Duplicate of #1189

**Closed as completed by alcatrazEscapee** 2020-05-05 21:55 UTC
Labels: duplicate
