### ISSUE TITLE
[1.12.2] Game Crashes a Few Seconds After Startup

### ISSUE THREAD

**Issue by KingofDogeII** [TerraFirmaCraft/TerraFirmaCraft#2014] opened 2022-07-12 22:55 UTC

**Comment by alcatrazEscapee** [comment] 2022-07-12 23:01
Great, I'll use my crash solving ESP... there it's fixed.

(Include a crash log *at least* if you want any sort of help.)

**Comment by KingofDogeII** [comment] 2022-07-12 23:03
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/12/22 7:02 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
	at net.acgaming.mcwfurnituretfc.util.RegistryHandler.onBlockRegister(RegistryHandler.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_194_RegistryHandler_onBlockRegister_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
	at net.acgaming.mcwfurnituretfc.util.RegistryHandler.onBlockRegister(RegistryHandler.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_194_RegistryHandler_onBlockRegister_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 464256272 bytes (442 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version        | Source                                        | Signature                                |
	|:----- |:---------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft              | 1.12.2         | minecraft.jar                                 | None                                     |
	| LCH   | mcp                    | 9.42           | minecraft.jar                                 | None                                     |
	| LCH   | FML                    | 8.0.99.99      | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                  | 14.23.5.2859   | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bdlib                  | 1.14.3.12      | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| LCH   | biomesoplenty          | 7.0.1.2445     | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| LCH   | chameleon              | 1.12-4.1.3     | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCH   | engineersdecor         | 1.1.4          | engineersdecor-1.12.2-1.1.4.jar               | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCH   | engineerstools         | 1.0.5          | engineerstools-1.12.2-1.0.5.jar               | None                                     |
	| LCH   | immersiveengineering   | 0.12-98        | ImmersiveEngineering-0.12-98.jar              | None                                     |
	| LCH   | chunkyexcavators       | 1.0            | chunkyexcavators-1.0.jar                      | None                                     |
	| LCH   | cucumber               | 1.1.3          | Cucumber-1.12.2-1.1.3.jar                     | None                                     |
	| LCH   | engineersdoors         | 0.9.1          | engineers_doors-1.12.2-0.9.1.jar              | None                                     |
	| LCH   | cfm                    | 6.3.1          | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCH   | immersive_energy       | 0.5.5          | Immersive+Energy-1.12.2-0.5.5.jar             | None                                     |
	| LCH   | immersivepetroleum     | 1.1.10         | immersivepetroleum-1.12.2-1.1.10.jar          | None                                     |
	| LCH   | immersiveposts         | 0.2.1          | ImmersivePosts-0.2.1.jar                      | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCH   | immersivetech          | 1.9.100        | MCTImmersiveTechnology-1.12.2-1.9.100.jar     | None                                     |
	| LCH   | mcwdoors               | 1.3            | mcw-doors-1.0.3-mc1.12.2.jar                  | None                                     |
	| LCH   | mcwfurnitures          | 1.0.1          | mcw-furniture-1.0.1-mc1.12.2beta.jar          | None                                     |
	| LCH   | tfc                    | 1.7.23.181     | TerraFirmaCraft-MC1.12.2-1.7.23.181.jar       | None                                     |
	| LCH   | mcwfurnituretfc        | 1.1.0          | mcw-furniture-tfc-1.1.0.jar                   | None                                     |
	| LCH   | mcwtrpdoors            | 1.0.2          | mcw-trapdoors-1.0.3-mc1.12.2.jar              | None                                     |
	| LCH   | questionablyimmersive  | @VERSION@      | questionablyimmersive-1.12.2-0.1.0.jar        | None                                     |
	| LCH   | corerm                 | 1.3.3          | RikMuldsCore_1.3.3.jar                        | None                                     |
	| LCH   | rsgauges               | 1.2.6          | rsgauges-1.12.2-1.2.6.jar                     | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCH   | sexmod                 | 1.5.2          | SchnurriTV's Sexmod-1.5.2.jar                 | None                                     |
	| LCH   | geckolib3              | 3.0.24         | SchnurriTV's Sexmod-1.5.2.jar                 | None                                     |
	| LCH   | winnetriesexpansionmod | 1.12.2-4.0.3.0 | winnetriesexpansionmod-4.0.3.0.jar            | None                                     |
	| LCH   | immersiveintelligence  | 0.2.1          | immersiveintelligence-0.2.1.jar               | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |
	| LCH   | industrialwires        | 1.7-36         | IndustrialWires-1.7-36.jar                    | 7e11c175d1e24007afec7498a1616bef0000027d |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  nihiltres.engineersdoors.common.asm.EngineersDoorsClassTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 460.89' Renderer: 'GeForce GTX 1660 SUPER/PCIe/SSE2'
	List of loaded APIs: 
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-98.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-98.jar
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor

**Comment by alcatrazEscapee** [comment] 2022-07-12 23:06
Duplicate of #1939

**Closed as completed by alcatrazEscapee** 2022-07-12 23:06 UTC
Labels: duplicate, Version: 1.12.x
