### ISSUE TITLE
Can't drink from rain when on all 4 Mud Blocks

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2121] opened 2022-09-13 16:09 UTC
Similar to the previous issue that reported humus, farmland and path blocks blocking rain drinking. Silty & Loam Mud Blocks too prevent the ability to drink from the rain.

https://user-images.githubusercontent.com/113080914/189952169-7f73eb32-5dea-4183-b65e-c79143870f12.mp4

**Comment by alcatrazEscapee** [comment] 2022-09-13 16:11
Duplicate of #2119

**Closed as completed by alcatrazEscapee** 2022-09-13 16:11 UTC
Labels: duplicate
