### ISSUE TITLE
Horse offspring jump strength very low

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1142] opened 2020-04-29 17:31 UTC
**Describe the bug**
Horse/donkey offspring jump strength very low. 

**To Reproduce**
Breed horse offspring and check jump strength (always 0.5?)

**Meta Info**
 - TFC Version: 0.X.X.135 on test server

**Comment by p0kes** [comment] 2020-05-12 18:53
JUMP_STRENGTH should be SharedMonsterAttributes.JUMP_STRENGTH in line 182 of EntityHorseTFC.java perhaps?

**Comment by DisasterMoo** [comment] 2020-05-14 17:04
there's no `JUMP_STRENGTH` in `SharedMonsterAttributes`. Horses have it's own attribute which is the one we are using it. The issue lies somewhere else, i will take a look when i can.

**Comment by p0kes** [comment] 2020-05-14 17:10
OK thanks, sorry for the misdirection :-)

**Comment by DisasterMoo** [comment] 2020-05-14 19:19
I've fixed waila implementation to show this, but in my tests i have found that they are working as intended, maybe it was a desync issue, or something related to old worlds don't know.

![image](https://user-images.githubusercontent.com/22617477/81976232-9eff8880-95fe-11ea-9af1-8ec24a5d60f9.png)
(Mule I bred to test, random spawned a male donkey and a female horse, only command used was to skip time)

**Comment by DisasterMoo** [comment] 2020-05-19 15:52
Seems to be working past build 144 (at least, on new worlds), Closing.

**Closed as completed by DisasterMoo** 2020-05-19 15:52 UTC
Labels: bug, fixed in dev
