### ISSUE TITLE
Axles turn the wrong direction when moved by a water wheel

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2612] opened 2024-01-05 19:52 UTC
https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/9ab8835a-170d-4ac3-9f6b-9776e36f0784

**Comment by alcatrazEscapee** [comment] 2024-01-06 03:29
Terrible issue report with no information, assuming duplicate of #2565

**Closed as not planned by alcatrazEscapee** 2024-01-06 03:29 UTC
Labels: duplicate

**Comment by MrHiTech123** [comment] 2024-01-08 19:29
Yes—that's it. Sorry
