### ISSUE TITLE
Deployers shouldn't try to Drink

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2697] opened 2024-05-08 03:33 UTC
Not sure of the configuration of the Create gantry, but a deployer on it apparently got through to the check drinkable event handler, which gets playerdata before checking if a fluid is present.

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/bd1244338724ae0e0d1000fd229347aa08583e6d/src/main/java/net/dries007/tfc/ForgeEventHandler.java#L1398

https://mclo.gs/7u2QxP2

This has occurred a few times on the LithicTFC server. No idea why ATMG2 or other 1.20 packs with Create haven't seen this as much?

**Comment by alcatrazEscapee** [comment] 2024-05-09 00:40
![2024-05-08_20 33 39](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35673674/97eb86c5-6de9-4e0e-b7af-1688a22c8660)

This setup is enough to reproduce a create deployer triggering a drink event handler, which should be perfectly legal. Player data is setup during `AttachCapabilitiesEvent<Entity>` which is part of the `Entity` constructor, which is invoked as part of the `DeployerFakePlayer` constructor that is ran in my testing. It then rejects drinking (because we have vanilla food data, and that indicates max thirst). Nothing here is problematic, but I'm more concerned with why in this case, we are missing player data. That seems to point at a larger issue, because fake player interaction does seem to work - again, in my testing.

We could bandaid this, but without a real way to test it I'd rather try and root cause this to find out _why_ there's missing player data. Potentially another mod interaction.

I also tested with a deployer on a gantry, no difference.

**Comment by Gaelmare** [comment] 2024-05-09 05:25
There apparently was no water, fluid, or filled aqueduct nearby. The drink
handler doesn't appear to check on the block raytraced to until after
player data is retrieved. No idea why the playerdata is empty, odd.

**Comment by alcatrazEscapee** [comment] 2024-05-09 10:59
That's entirely irrelevant. This setup works equally fine without a fluid block there, as we already have a check that the drinkable is not null. It **does not need** to check if a fluid is present, and changing the order of these checks would just appear to hide the issue behind a more specific situation.

**Comment by alcatrazEscapee** [comment] 2024-10-31 16:18
Closing as unreproducible.

**Closed as completed by alcatrazEscapee** 2024-10-31 16:18 UTC
Labels: mod conflict, Version: 1.20.x
