### ISSUE TITLE
Bushes spawn on Ice

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#669] opened 2019-12-15 13:21 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Not this.
2. What actually happened instead (i.e. what was the bug)
Bushes spawn on Ice.

**Meta Info**
 - TFC Version: 0.X.X.107 on test server.
![2019-12-15_12 07 21](https://user-images.githubusercontent.com/58256171/70863241-c95cf500-1f3d-11ea-97fa-11c27246a411.png)

**Comment by alcatrazEscapee** [comment] 2019-12-15 15:46
Duplicate of #602

**Closed by alcatrazEscapee** 2019-12-15 15:46 UTC
Labels: unconfirmed bug
