### ISSUE TITLE
Teleportation crash

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#39] opened 2019-04-09 00:00 UTC
When teleporting over long distances, there's a good chance that the game will crash. Here's one crash log among many: https://pastebin.com/U844A9LN

**Comment by alcatrazEscapee** [comment] 2019-04-09 00:24
After teleporting ~50 times 10k blocks or more I can't reproduce this crash.
1. Does it happen with only TFC installed?
2. If so, what specific steps are you doing that causes a crash (world, tp, seed, etc.)

**Comment by JonJonsonsSon** [comment] 2019-04-09 23:20
Yes
Teleport anywhere, then move about 10-16 steps away from your current location using whatever randomly generated seed the world gave you. The crash isn't 100% guaranteed to happen, but when it does, you'll usually crash 1-3 more times upon logging back in and trying to move forward
New crash log with only TFC installed: https://pastebin.com/kDMxjb2i
2nd crash log upon logging back in and attempting to move forward 1 block: https://pastebin.com/hYcLa6Ef

**Comment by alcatrazEscapee** [comment] 2019-04-10 00:05
I can't reproduce this, (I've tried many times, in addition to the same world that crashed you, with the same teleport coordinates.) nor do I see any reason why that crash would be happening. Do you have a specific world / seed / teleport location that is guaranteed to crash for you? Because I have no way to fix this if I can't make it happen.

**Comment by JonJonsonsSon** [comment] 2019-04-10 00:32
Nah, it seems to be entirely random for me. Also, I'm using Forge v14.23.5.2768. Could that have anything to do with it?

**Comment by alcatrazEscapee** [comment] 2019-04-10 00:34
That is the forge version that we are using as well. This is driving me bananas

**Comment by JonJonsonsSon** [comment] 2019-04-10 00:41
And if it helps narrow things down, I've been experiencing this crash since early September of 2018, so the crash isn't being caused by any recent changes

**Comment by Konlii** [comment] 2019-04-21 14:10
So, I actually get this crash every now and then on initial worldgen in my dev environment.
[crash-2019-04-17_15.39.28-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3101254/crash-2019-04-17_15.39.28-server.txt)

**Comment by alcatrazEscapee** [comment] 2019-04-21 15:43
So I have absolutely no idea what is causing this. I still haven't experienced it myself, despite a lot of trying. If it has a specific cause, it is buried under layers of `GenLayerTFC` and other worldgen nonsense that is probably going to be re-written anyway for 1.14. I am going to attempt to stop the crash without actually fixing the bug, hopefully it will be useful and then maybe it can be fixed layer or during rewrites.

**Comment by alcatrazEscapee** [comment] 2019-05-03 14:14
So I think I have ducktape fixed this, I'm closing unless it can be produced again. Re-open this issue if it is still a problem

**Closed by alcatrazEscapee** 2019-05-03 14:14 UTC
Labels: bug
