### ISSUE TITLE
Anvil plans broken in multiplayer after version 3.2.7

### ISSUE THREAD

**Issue by zersal** [TerraFirmaCraft/TerraFirmaCraft#2822] opened 2024-11-09 23:13 UTC
When using an anvil in multiplayer on the newest version when trying to work an ingot you can open the plan menu and see the available recipes but when you click on one nothing happens, it just closes the menu.
The last version I found to work was 3.2.7.
Singleplayer is not affected.

**Comment by ChococookieOS** [comment] 2024-11-10 19:58
I just came here, two second this. 
Server is running forge-1.20.1-47.3.11. TFC:NG mod version (3.2.10)
What I found out currently works is the following:

1. Heat Ingot sufficiently
2. Put it in the anvil (Hammer and flux already in place)
3. Select a plan (The menu will close and there will be no indication of a plan being selected)
4. click on one of the green forge options
5. Take the ingot out of the slot of the anvil and place it in your inventory. (Item needs to detach from mouse cursor)
6. Put the ingot back into the anvil
7. Everything shows properly in the anvil menu
8. Once you click the next forge action the menu breaks again.

If you want to play the 3.2.10 version @zersal 
take out the ingot and put it back in after every step. Annoying but playable :)

I would really love to see this bug fixed. Is there anything else I can help the devs with?

**Comment by KittenRaee** [comment] 2024-11-11 10:06
> Annoying but playable :)

I wouldn't say playable, imagine working copper that gets too cold when you sneeze at it, let alone do that silly little dance

**Comment by ChococookieOS** [comment] 2024-11-11 11:17
> I wouldn't say playable

Yeah I did that silly little dance yesterday with copper because I had no choice but after having forged 4 tools in 30 minutes it broke me. That's why I came here ^^

**Comment by ChococookieOS** [comment] 2024-11-11 14:02
I Investigated a bit and here are my findings:

- Since @zersal mentioned that it was still working in 3.2.7 I looked at the diff and could pinpoint the culprit.
- During the issue #2753 `ItemStackCapabilitySync.java` and `FriendlyByteBufMixin.java` were changed to (at least from what I understand) allow itemstack synchronisation with the vanilla protocol allowing people to play on vanilla servers with the mod installed.
- This leads to `Forging.java#getRecipe(Level level)` returning `null` in various cases for example in` AnvilBlockEntity.java#148` or `AnvilScreen.java#81` under the initially described conditions.

Since I currently do not play on any vanilla server I locally reverted the two files two version 3.2.7 while keeping the rest on 3.2.10. It works and compiles perfectly.

Unfortunatly I have not worked or looked into any minecraft networking protocols and can not fix this properly myself right now. But I hope that with the information provided someone can have a look at this. Maybe ItemStackCapabilitySync sounds quite broad so it might affect other areas as well. I havent progressed the mod far enough to tell.
For further questions I am available at discord: C0d3v

**Comment by VademoN228** [comment] 2024-11-17 10:00
Yesterday my friend and i played on a local network. The host was my friend. And templates were not displayed in the anvil, while my friend has seen them. After we decided to try me in the role of a host, and now for me templates were displayed, but he did not see them.

**Comment by GrimWolf47** [comment] 2024-11-18 21:42
I'm also having this issue, tried removing all of my mods, (Except tfc) and tried multiple different hosting methods, but the issue persist.. It's still sorta playable since I can still see the plans as the host,, but my friends cannot see the plans at all (used E4mc and Essentials for hosting)

**Comment by thevortex** [comment] 2024-11-24 01:55
any news on this or should we just revert to 3.2.7 for the time being?

**Comment by wchristian** [comment] 2024-11-24 02:03
Just ran into this as well, and a chunk with a bunch of stuff got deleted.

Why is this marked as "unconfirmed"?

**Comment by wchristian** [comment] 2024-11-24 17:29
For the people coming here because of Gravitas2: We resolved the matter for the moment by downgrading Gravitas2 entirely instead of just TFC.

**Closed as completed** 2024-11-28 00:30 UTC
Labels: bug, fixed in dev, Version: 1.20.x
