### ISSUE TITLE
Wooden buckets stacking issue

### ISSUE THREAD

**Issue by M8-u** [TerraFirmaCraft/TerraFirmaCraft#1294] opened 2020-05-19 20:23 UTC
I expected the empty wooden bucket to stack with another empty wooden bucket. The empty bucket has "0 nbt tags" in its description and will not stack with other empty buckets.
Screenshots:
![2020-05-19_14 20 40](https://user-images.githubusercontent.com/53875064/82374242-c4b8d300-99ec-11ea-8b7f-ebd1d4e18f71.png)
![2020-05-19_14 20 41](https://user-images.githubusercontent.com/53875064/82374187-ae127c00-99ec-11ea-86ec-f19783b11dcb.png)

**To Reproduce**
1. Milk a willing cow.
2. Then empty the bucket by click on a barrel. This will NOT work by emptying the bucket on the ground.

**Meta Info**
 - TFC Version: 1.2.1.44
Can be reproduced in creative with a milkable cow and a barrel.

**Comment by alcatrazEscapee** [comment] 2020-05-20 12:06
Duplicate of #946, but apparently still an issue.

**Closed as completed by alcatrazEscapee** 2020-05-20 12:06 UTC
Labels: duplicate
