### ISSUE TITLE
terrafirmacraft wont accept my java version 

### ISSUE THREAD

**Issue by UnitedCreeper** [TerraFirmaCraft/TerraFirmaCraft#2716] opened 2024-05-31 01:16 UTC
i was playing mc on a modpack i made, i was chilling for a solid hour, i turned off minecraft, 30 minutes later i try join back and it wont work, i try everything recomended but it wouldnt work, its specifically terrafirma i checked
![image_2024-05-31_021643017](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/171302603/c36a0646-1b35-451a-abe8-364888a76cd5)
[latest.log](https://github.com/user-attachments/files/15507228/latest.log)

**Comment by alcatrazEscapee** [comment] 2024-05-31 01:23
Duplicate of #2610

**Closed as completed by alcatrazEscapee** 2024-05-31 01:23 UTC
Labels: duplicate, Version: 1.20.x
