### ISSUE TITLE
TFCT: Sheets don't stack after placed in world and broken

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1212] opened 2020-05-07 04:22 UTC
Looks like the item block is retaining empty NBT data like wooden buckets were in #946 ?

 - TFC Version: build 140

**Comment by eerussianguy** [comment] 2020-05-08 03:28
Let's add a key that stacks them, like food

**Comment by alcatrazEscapee** [comment] 2020-05-09 19:50
> Let's add a key that stacks them, like food
No, if there's a bug, let's fix the bug.

That said, I cannot reproduce in SMP or SSP. Everything seems to be working as intended and I see no possible code paths through which this should be possible.

Are you sure they just weren't different temperatures?

**Comment by Gaelmare** [comment] 2020-05-10 00:07
Pretty sure one was placed and then broken. I'll see if I can find it on
their stream.

**Comment by Gaelmare** [comment] 2020-05-10 22:56
https://clips.twitch.tv/BadCuriousCakeTBTacoRight
that's build 140

**Comment by DisasterMoo** [comment] 2020-05-19 15:55
If this happens again, would be awesome to get a world save to check if this is NBT related or something. Since neither me nor Alc could reproduce, Closing (reopen with reproduction steps or world save if happens again).

**Closed as completed by DisasterMoo** 2020-05-19 15:55 UTC
Labels: working as intended
