### ISSUE TITLE
Loom crashes with null recipe from TFC Metallum

### ISSUE THREAD

**Issue by AlexRover** [TerraFirmaCraft/TerraFirmaCraft#1580] opened 2020-09-29 18:53 UTC
[crash-2020-09-30_00.47.17-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5301255/crash-2020-09-30_00.47.17-client.txt)

hello, when you try to use the loom, the world collapses, I made the recipe, everything is like in the wiki here on the site, I don't know what is wrong

**Comment by alcatrazEscapee** [comment] 2020-09-30 20:00
No idea what's happened here. Full log + reproduction with only TFC please.

**Comment by AlexRover** [comment] 2020-09-30 20:04
Um, this log from the crash folder, where can I get the full one?
Only with TFC it will not work, I am weaving from TFC: Metallum iron wire and I want to get an iron mesh Magneticraft

**Comment by alcatrazEscapee** [comment] 2020-09-30 20:13
> `logs/debug.log`, in the minecraft directory

**Comment by AlexRover** [comment] 2020-09-30 20:16
[2020-09-30-7.log.gz](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5308044/2020-09-30-7.log.gz)

**Comment by DisasterMoo** [comment] 2020-09-30 20:28
> Um, this log from the crash folder, where can I get the full one?
> Only with TFC it will not work, I am weaving from TFC: Metallum iron wire and I want to get an iron mesh Magneticraft

Oh, I was surprised but it's actually TFCTech's iron wire, Metallum only registers new metals. Also, it seems to be a modpack with a modified recipe, since you are trying to get Magneticraft's thing from it. If it's a known modpack, can you please link it here so we can better diagnose the script?

**Comment by AlexRover** [comment] 2020-09-30 20:31
The basis is taken from the Internet, but I put mods there and now I'm trying to connect everything

**Comment by alcatrazEscapee** [comment] 2022-07-20 21:07
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.

**Closed as completed by alcatrazEscapee** 2022-07-20 21:07 UTC
Labels: needs update, unconfirmed bug, mod conflict, Version: 1.12.x
