### ISSUE TITLE
Sandwiches randomly lose nutrition, expiration, and saturation data

### ISSUE THREAD

**Issue by tst5000** [TerraFirmaCraft/TerraFirmaCraft#1061] opened 2020-04-21 00:54 UTC
**Describe the bug**
1. I expected my sandwiches to retain their nutrition, saturation, and expiration date.
2. The opposite of the above happens, sandwiches randomly losing said stats
3. Screenshot of example included

**To Reproduce**
Attention to detail is important!
1. Create sandwich
2. Wait some random amount of time, do various things to sandwich (such as storing it in a ceramic vessel)
3. Sandwich will randomly lose nutrition.

**Meta Info**
 - TFC Version: 1.12-1.0.5.132
![2020-04-20_20 53 12](https://user-images.githubusercontent.com/52762828/79813200-fa649080-8348-11ea-9e47-8abc70bcc72f.png)

**Comment by alcatrazEscapee** [comment] 2020-04-21 00:56
Duplicate of #944

**Closed as completed by alcatrazEscapee** 2020-04-21 00:56 UTC
Labels: duplicate
