### ISSUE TITLE
Horses teleport really far away when dismounting

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1293] opened 2020-05-19 02:15 UTC
**Meta Info**
 - TFC Version: 0.X.X.142
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment] 2020-05-19 02:48
Duplicate of #984 which is a known mojang bug

**Closed as completed by DisasterMoo** 2020-05-19 02:48 UTC
Labels: duplicate
