### ISSUE TITLE
Gold Pan 

### ISSUE THREAD

**Issue by NicelysBabyGirl** [TerraFirmaCraft/TerraFirmaCraft#1153] opened 2020-05-02 15:54 UTC
**Describe the bug** Gold pan is showing there is items still in it when it is empty 
Make sure to include:
1. What did you expect to happen? when empty should just be a pan with no content in it
2. What actually happened instead (i.e. what was the bug) is showing sand/gravel in pan when is empty
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: 0.X.X.XX
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment] 2020-05-03 20:08
Duplicate of #885

**Closed as completed by DisasterMoo** 2020-05-03 20:08 UTC
Labels: duplicate
