### ISSUE TITLE
Unable to run TFC in dev env with other mods (?)

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [TerraFirmaCraft/TerraFirmaCraft#503] opened 2019-10-19 15:02 UTC
---
Official goodmc request
---

Crash report
https://pastebin.com/Uybf8hhD

does not compile the mod with TFC
when we run the mod in the development environment
we run Minecraft
our mod compiles and runs
plus additional mods that you threw in the mods folder
and all mods run fine, but not TFC
throws an error

**Meta Info**
 - TFC Version: 0.25.2.86

**Comment by alcatrazEscapee** [comment] 2019-10-19 16:18
I can't reproduce this. This looks like your dev environment is broken, or your missing parts of TFC or the access transformer somehow.
1) Can you reproduce this without any other mods?
2) Can you reproduce this not in a dev environment?
3) Are you loading TFC as a library or via sticking it in the mods folder?

**Comment by Meldexun** [comment] 2019-11-20 10:11
I get the same error. I just created a new workspace with Forge 14.23.5.2847 and added TerraFirmaCraft-MC1.12.2-0.26.4.94 as a library and started the game.

**Comment by alcatrazEscapee** [comment] 2019-11-20 11:54
Make sure you are using the same MCP mapping version as TFC is if you are using it by dropping it in `/libs`

**Comment by Meldexun** [comment] 2019-11-20 15:21
That didn't change anything.

**Comment by Meldexun** [comment] 2019-12-05 16:03
I tested it again and using the deobf version with the correct mappings works for me.

**Comment by alcatrazEscapee** [comment] 2019-12-10 02:26
If there's no other information to be had, I'll close this then.

**Closed by alcatrazEscapee** 2019-12-10 02:26 UTC
Labels: unconfirmed bug
