### ISSUE TITLE
Snowfall makes Blast Furnace pop off.

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#625] opened 2019-12-05 23:32 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Blast furnace to stay put during snowfall.
2. What actually happened instead (i.e. what was the bug)
Snowfall made Blast Furnace pop off, in perhaps the same way as #570 

**To Reproduce**
Attention to detail is important!
1. Do '...'
Build blast furnace during snowfall.

**Meta Info**
 - TFC Version: 0.X.X.103 on test server.

**Comment by DisasterMoo** [comment] 2019-12-06 03:09
Duplicate of #570

**Closed** 2020-01-08 01:35 UTC
Labels: bug, fixed in dev
