### ISSUE TITLE
Dupe bug with vessels

### ISSUE THREAD

**Issue by Ozzymud** [TerraFirmaCraft/TerraFirmaCraft#2396] opened 2023-05-12 00:02 UTC
TerraFirmaCraft-Forge-1.18.2-2.2.15

Playing the current version of the auto-terrafirmacraft modpack on it's official server.

As far as I've always known, this is a lag/latency thing that only works when playing on a server. I remember originally seeing it with loot bags and like the iron backpacks mod back in the day.

The dupe is as such.

Place items in a small vessal.
Press Q to drop as close as possible to clicking the right mouse button to open it.
If successful you will see the vessel fly out to the ground while also remaining in the hotbar and opening.
Remove the items from the vessal.
Pick up the vessal on ground and items are still there.
Repeat as often as you like.

It is finicky, if tps > 18 it is VERY hard to do. with tps at 10... I can do it almost EVERY time.

**Comment by alcatrazEscapee** [comment] 2023-05-12 22:37
Cannot confirm that this is fixed as I've not managed to reproduce it, with or without my fix, but is likely resolved in part due to the fix for #2383

**Closed as completed** 2023-05-16 13:40 UTC
Labels: fixed in dev, unconfirmed bug, Version: 1.18.x
