### ISSUE TITLE
Z-fighting when a scribing table is placed on top of another scribing table

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2438] opened 2023-06-01 00:16 UTC
![2023-05-31_13 20 25](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/fb7414c3-7ebc-410f-bd4b-d49358b84661)

**Comment by alcatrazEscapee** [comment] 2023-06-01 00:33
Duplicate of #2434

**Closed as not planned by alcatrazEscapee** 2023-06-01 00:33 UTC

**Comment by muzikbike** [comment] 2023-08-29 15:01
This still happens in 2.2.29 despite #2434 being fixed.
