### ISSUE TITLE
Wooly animals are extremely fast

### ISSUE THREAD

**Issue by gor1ck** [TerraFirmaCraft/TerraFirmaCraft#2512] opened 2023-09-21 18:23 UTC
I used grains to lure some cattle. No any problems with cows and goats, but two sheeps and two alpakas were jerkily approaching me with incredible acceleration, and on an uneven surface or ice they were just flying away somewhere in the distance, for several chunks. I managed to corral three of them, but the fourth crashed to his death after another flight.

**Comment by alcatrazEscapee** [comment] 2023-09-21 23:23
Duplicate of #2341

**Closed as completed by alcatrazEscapee** 2023-09-21 23:23 UTC
Labels: duplicate
