### ISSUE TITLE
More convenient way to make bread dough

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1363] opened 2020-05-30 01:28 UTC
Each bucket should be able to make up to 8 flour into dough by putting the four around the bucket in a crafting bench.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment] 2020-05-30 03:06
Suggestions should be discussed in discord first. ~~Feature (make dough easier to make) duplicate of #1337~~
Actually, the feature in #1337 was rejected because it is not possible since it conflicts with other recipes. Although this one is still rejected because you can use CT to change it.

**Closed as completed by DisasterMoo** 2020-05-30 03:06 UTC
Labels: working as intended
