### ISSUE TITLE
Crunchy Salad typo'd as "Cruchy Salad"

### ISSUE THREAD

**Issue by DanteTorn** [TerraFirmaCraft/TerraFirmaCraft#1763] opened 2021-05-08 03:47 UTC
**Describe the bug**
Crunchy salad is misspelled as "cruchy salad."
This probably hasn't been noticed yet because AFAICT there is no "vanilla" way to make one. The only way I've found to make it at all is using FirmaLife dried pineapple. I assume from this that "crunchy" salads are salads with grains in them, because dried pineapple has 0.1 grain and 0.1 protein.
![image](https://user-images.githubusercontent.com/35230199/117524791-fbe61280-afb6-11eb-8da5-912c7e02201d.png)

**To Reproduce**
Find it in the creative menu in normal TFC.
OR
Make a salad using dried pineapple with FirmaLife also installed.

**Meta Info**
 - TFC Version: 1.7.18.176
 - Tested with both TechNodeFirmaCraft and a clean install of just Forge and TFC

**Comment by eerussianguy** [comment] 2021-05-14 13:49
Sorry didn't mean for you to close this. Thought it was clear I was kidding around by marking a typo as intended

**Comment by DanteTorn** [comment] 2021-05-16 21:01
> 
> 
> Sorry didn't mean for you to close this. Thought it was clear I was kidding around by marking a typo as intended

Didn't occur to me it could've been a joke. I was a little confused by it though. All good.

**Comment by eerussianguy** [comment] 2021-05-16 21:11
Why did you close it again?

FWIW alc and I both have power over issues here. Just assume that we will close stuff when we like

**Comment by DanteTorn** [comment] 2021-05-22 20:13
My apologies. Habit.

**Closed as completed** 2021-06-03 13:47 UTC
Labels: bug, fixed in dev, Version: 1.12.x
