### ISSUE TITLE
[1.18.2-2.1.1] Anvil Plans menu not working in survival worlds

### ISSUE THREAD

**Issue by Eario** [TerraFirmaCraft/TerraFirmaCraft#2059] opened 2022-08-28 05:42 UTC
When clicking the plans menu button in an anvil in survival mode, nothing pops up - the anvil GUI stays the same, making any form of advanced metalworking impossible in survival.

**Comment by alcatrazEscapee** [comment] 2022-08-28 12:52
Cannot reproduce - the anvil plan GUI is opening perfectly fine.

My guess is you are using a anvil of a too low tier to work something, in which case no recipes will show up because of the tier difference. That or you are trying to work something that doesn't exist, in which case no, the plan menu will not show up.

**Comment by Ironcanon** [comment] 2022-08-31 12:22
They might be talking about stone anvils; While it does mention in the guide book that they can only be used to weld teir 1 metals, stone anvils do have a plan button that does nothing when clicked (even if a tier 1 ingot is in the anvil) which could be confusing if they missed the aformentioned information in the guide.

**Comment by alcatrazEscapee** [comment] 2022-09-24 14:49
Closing as it's been a month with no update.

**Closed as completed by alcatrazEscapee** 2022-09-24 14:49 UTC
Labels: working as intended, Version: 1.18.x

**Comment by ScottCowe** [comment] 2023-11-02 19:15
I am having this issue as well - however for me it is in both creative and survival where I cannot even open the plans menu on the anvil, nor can I weld ingots.

**Comment by Danilaa56** [comment] 2024-03-06 21:33
I have the same issue on MacOS Forge 1.20.1-3.1.9. Plans tab cannot be opened both in survival and creative mods.

**Comment by Danilaa56** [comment] 2024-03-07 21:04
@ScottCowe. It's not very obvious. I have faced this problem myself.

In order to weld items, you need to place the recipe items in the anvil (e.g., 2 hot ingots and a flux) and right-click on the anvil with hammer.
