### ISSUE TITLE
Dupe of food

### ISSUE THREAD

**Issue by officialGerero** [TerraFirmaCraft/TerraFirmaCraft#1581] opened 2020-09-29 19:27 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Either ignore pressing in inventory crafting or consume items
2. What actually happened instead (i.e. what was the bug)
So when you put any food item into inventory crafting and press x it doesn`t consume items, but gives you the result

**To Reproduce**
Attention to detail is important!
1. Open inventory get 2 same food items
2. Put 1 in the inventory crafting table
3. Hover over the one in your inventory press x
4. To repeat take and put back item in the crafting gui

**Meta Info**
 - TFC Version: 0.1.7.3.161 also tested latest
 - Were any other mods included? Can you reproduce it without these other mods?
Yes there were some mods, and i could reproduce the dupe without them

**Comment by alcatrazEscapee** [comment] 2020-09-30 20:03
Duplicate of #1239

**Closed as completed by alcatrazEscapee** 2020-09-30 20:03 UTC
Labels: duplicate
