### ISSUE TITLE
CTD with GeckoLib mod installed

### ISSUE THREAD

**Issue by Renexan95** [TerraFirmaCraft/TerraFirmaCraft#2285] opened 2023-01-13 11:36 UTC
As per title the mod crash with GeckoLib
My specs are

CPU - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU - NVIDIA GeForce RTX 2070 4GB
RAM - 16GB DDR4

Here's the report:

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/12/23, 2:35 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.0-universal.jar%23133!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.2.0-universal.jar%23133!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:werewolves.mixins.json:client.ClientModLoaderAccessor,pl:mixin:APP:controllable.mixins.json:client.ClientModLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:557) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc46766.MinecraftClientMixin,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,re:classloading,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc46766.MinecraftClientMixin,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc46766.MinecraftClientMixin,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc46766.MinecraftClientMixin,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23128!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.0.1-jre.jar%2329!/:?] {}
-- MOD tfc --
Details:
	Mod File: /D:/Games/MinecraftAT/instances/TerraFirmaCraft1182/mods/TerraFirmaCraft-Forge-1.18.2-2.2.3.jar
	Failure message: TerraFirmaCraft (tfc) encountered an error during the common_setup event phase
		java.lang.NullPointerException: Cannot set config value without assigned Config object present
	Mod Version: 2.2.3
	Mod Issue URL: https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues
	Exception message: java.lang.NullPointerException: Cannot set config value without assigned Config object present
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.0.1-jre.jar%2329!/:?] {}
	at net.minecraftforge.common.ForgeConfigSpec$ConfigValue.set(ForgeConfigSpec.java:873) ~[forge-1.18.2-40.2.0-universal.jar%23133!/:?] {re:classloading,re:mixin}
	at net.dries007.tfc.world.TFCWorldType.overrideDefaultWorldType(TFCWorldType.java:47) ~[TerraFirmaCraft-Forge-1.18.2-2.2.3.jar%23115!/:2.2.3] {re:classloading}
	at net.dries007.tfc.TerraFirmaCraft.setup(TerraFirmaCraft.java:150) ~[TerraFirmaCraft-Forge-1.18.2-2.2.3.jar%23115!/:2.2.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.0.jar%23130!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.0.jar%23129!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1238765984 bytes (1181 MiB) / 3456106496 bytes (3296 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f10
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2698
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2115
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 36800.36
	Virtual memory used (MB): 28969.67
	Swap memory total (MB): 20574.89
	Swap memory used (MB): 7070.98
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx10240M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 essential-loader TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
		kotlinforforge@3.6.0
	Mod List: 
		notenoughcrashes-4.2.0+1.18.2-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.2.0+1.18.2        |SIDED_SETU|Manifest: NOSIGNATURE
		Fastload-Reforged-2.6.9+1.18.2.jar                |Fastload                      |fastload                      |2.6.9+1.18.2        |SIDED_SETU|Manifest: NOSIGNATURE
		tfctweaks-1.4.jar                                 |TFCTweaks                     |tfctweaks                     |1.4                 |SIDED_SETU|Manifest: NOSIGNATURE
		TFC Decoration 1.18.2-1.1.2.jar                   |TFC Decoration                |tfc_decoration                |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.36.199.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.36.199   |SIDED_SETU|Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |SIDED_SETU|Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+22.jar               |Controlling                   |controlling                   |9.0+22              |SIDED_SETU|Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.5.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.5      |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |SIDED_SETU|Manifest: NOSIGNATURE
		CustomPlayerModels-1.18-0.6.3a.jar                |Customizable Player Models    |cpm                           |0.6.3a              |SIDED_SETU|Manifest: NOSIGNATURE
		weather2-1.18.2-2.7.4.jar                         |Weather2                      |weather2                      |1.18.2-2.7.4        |SIDED_SETU|Manifest: NOSIGNATURE
		starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de |SIDED_SETU|Manifest: NOSIGNATURE
		balm-3.2.1+0.jar                                  |Balm                          |balm                          |3.2.1+0             |SIDED_SETU|Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.9.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.9             |SIDED_SETU|Manifest: NOSIGNATURE
		dynview-1.18.2-2.8.jar                            |Dynamic view distance         |dynview                       |2.3                 |SIDED_SETU|Manifest: NOSIGNATURE
		immersive_armors-1.5.2+1.18.2-forge.jar           |Immersive Armors              |immersive_armors              |1.5.2+1.18.2        |SIDED_SETU|Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.198.jar             |CraftTweaker                  |crafttweaker                  |9.1.198             |SIDED_SETU|Manifest: NOSIGNATURE
		cloth-config-6.3.81-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.3.81              |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |SIDED_SETU|Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.14.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.14       |SIDED_SETU|Manifest: NOSIGNATURE
		tfcsupplementaries-1.1.jar                        |TFC Supplementaries           |tfcsupplementaries            |1.1                 |SIDED_SETU|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.18.2-14.0.3.jar            |CraftingTweaks                |craftingtweaks                |14.0.3              |SIDED_SETU|Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TerraFirmaCraft-Forge-1.18.2-2.2.3.jar            |TerraFirmaCraft               |tfc                           |2.2.3               |ERROR     |Manifest: NOSIGNATURE
		waterflasks-2.0.4.jar                             |TFC Water Flasks              |waterflasks                   |2.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedbackpacksvh-1.18.2-1.0.5.13.jar      |Sophisticated Backpacks Vault |sophisticatedbackpacksvh      |1.18.2-1.0.5.13     |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.18.40.773.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.40.773  |SIDED_SETU|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |SIDED_SETU|Manifest: NOSIGNATURE
		ToolBelt-1.18.2-1.18.9.jar                        |Tool Belt                     |toolbelt                      |1.18.9              |SIDED_SETU|Manifest: NOSIGNATURE
		Reblured-1.18.2-1.2.0.jar                         |ReBlured                      |reblured                      |1.18.2-1.2.0        |SIDED_SETU|Manifest: NOSIGNATURE
		ColaMixinConfig-v1.0.2.jar                        |ColaConfig                    |caffeineconfig                |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		BRVSB-1.0.3-mc1.18.2.jar                          |Better Rubidium Video Settings|bsvsb                         |1.0.3-mc1.18.2      |SIDED_SETU|Manifest: NOSIGNATURE
		smoothboot(reloaded)-mc1.18.2-0.0.2.jar           |Smooth Boot (Reloaded)        |smoothboot                    |0.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		createendertransmission-1.0.0.jar                 |Create Ender Transmission     |createendertransmission       |1                   |SIDED_SETU|Manifest: NOSIGNATURE
		tfcambiental-2.2.0-1.18.2.jar                     |TFC Ambiental                 |tfcambiental                  |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.8.jar                   |Flywheel                      |flywheel                      |0.6.8-97            |SIDED_SETU|Manifest: NOSIGNATURE
		tfcreate-1.0.jar                                  |TFCreate                      |tfcreate                      |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |SIDED_SETU|Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |SIDED_SETU|Manifest: NOSIGNATURE
		rubidium-extra-0.4.16+mc1.18.2-build.57.jar       |Rubidium Extra                |sodiumextra                   |0.4.16+mc1.18.2-buil|SIDED_SETU|Manifest: NOSIGNATURE
		SewingKit-1.18.2-1.5.9.jar                        |Sewing Kit                    |sewingkit                     |1.5.9               |SIDED_SETU|Manifest: NOSIGNATURE
		mna-1.7.2.9.jar                                   |Mana and Artifice             |mna                           |1.7.2.7             |SIDED_SETU|Manifest: NOSIGNATURE
		entityculling-forge-mc1.18-1.5.1.jar              |EntityCulling                 |entityculling                 |1.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		armourersworkshop-forge-1.18.2-2.0.0-beta.8.jar   |Armourer's Workshop           |armourers_workshop            |2.0.0-beta.8        |SIDED_SETU|Manifest: 58:d0:3b:4b:a0:4b:43:fb:59:0f:27:f5:39:d5:65:de:9a:24:ee:2e:15:48:b1:4f:78:1a:e1:ef:cd:a4:d9:0a
		swashbucklers2.4.jar                              |HalsPirateMod                 |hpm                           |2.3                 |SIDED_SETU|Manifest: NOSIGNATURE
		tfchomestead-1.0.3-1.18.2.jar                     |TFC Homestead                 |tfchomestead                  |0.0.0-indev         |SIDED_SETU|Manifest: NOSIGNATURE
		coroutil-1.18.1-1.2.43.jar                        |CoroUtil                      |coroutil                      |1.18.1-1.2.43       |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-4.10.88-forge.jar                    |Architectury                  |architectury                  |4.10.88             |SIDED_SETU|Manifest: NOSIGNATURE
		antiqueatlas-7.0.3-forge-mc1.18.2.jar             |Antique Atlas                 |antiqueatlas                  |7.0.3-forge-mc1.18.2|SIDED_SETU|Manifest: NOSIGNATURE
		Vampirism-1.18.2-1.8.8.jar                        |Vampirism                     |vampirism                     |1.8.8               |SIDED_SETU|Manifest: NOSIGNATURE
		Werewolves-1.18.2-1.0.0.1.jar                     |Werewolves                    |werewolves                    |1.0.0.1             |SIDED_SETU|Manifest: NOSIGNATURE
		ferritecore-4.2.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.2               |SIDED_SETU|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		AI-Improvements-1.18.2-0.5.2.jar                  |AI-Improvements               |aiimprovements                |0.5.2               |SIDED_SETU|Manifest: NOSIGNATURE
		extendedflywheels-1.2.5-1.18.2-0.5.e.jar          |Extended Flywheels            |extendedflywheels             |1.2.5-1.18.2-0.5.e  |SIDED_SETU|Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.g.jar                         |Create                        |create                        |0.5.0.g             |SIDED_SETU|Manifest: NOSIGNATURE
		extendedgears-1.18.2-0.5.0g-1.1.1.jar             |Extended Cogs                 |extendedgears                 |1.18.2-0.5.0g-1.1.1 |SIDED_SETU|Manifest: NOSIGNATURE
		debugify-1.11.0-forge-1.18.2.jar                  |Debugify                      |debugify                      |1.11.0              |SIDED_SETU|Manifest: NOSIGNATURE
		BetterF3-3.0.0-Forge-1.18.2.jar                   |BetterF3                      |betterf3                      |3.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.18-1.8-Forge.jar |CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.8                 |SIDED_SETU|Manifest: NOSIGNATURE
		controllable-0.16.6-1.18.2.jar                    |Controllable                  |controllable                  |0.16.6              |SIDED_SETU|Manifest: NOSIGNATURE
		valhelsia_core-forge-1.18.2-0.4.0.jar             |Valhelsia Core                |valhelsia_core                |1.18.2-0.4.0        |SIDED_SETU|Manifest: NOSIGNATURE
		forbidden_arcanus-1.18.2-2.1.1.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.18.2-2.1.1        |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |SIDED_SETU|Manifest: NOSIGNATURE
		dreadsteel-1.18.2-1.1.4.jar                       |Dreadsteel                    |dreadsteel                    |1.18.2-1.1.4        |SIDED_SETU|Manifest: NOSIGNATURE
		createaddition-1.18.2-20221219a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20221219a    |SIDED_SETU|Manifest: NOSIGNATURE
		Essential (forge_1.18.2).jar                      |Essential                     |essential                     |11642+deploy-staging|SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 4230a389-5d2f-45e8-872c-8c1c5e8f0bcd
	FML: 40.2
	Forge: net.minecraftforge:40.2.0
	Flywheel Backend: GL33 Instanced Arrays
	Suspected Mods: Minecraft (minecraft), Forge (forge)
```

**Comment by alcatrazEscapee** [comment] 2023-01-13 13:18
I cannot reproduce this crash, using the versions of TFC + Patchouli + Gekolib listed. You have a lot of other mods in this crash report, does it occur just with TFC + Patchouli + Gekolib?

Moreover, it seems something is screwing up with Forge's config file which we attempt to modify. Can you upload your config file for `forge-common.toml`?

**Comment by Renexan95** [comment] 2023-01-14 14:44
Here the file, it's so weird... I'll do another instance with only the two mods

```
#General configuration settings
[general]
	#Defines a default world type to use. The vanilla default world type is represented by 'default'.
	#The modded world types are registry names which should include the registry namespace, such as 'examplemod:example_world_type'.
	defaultWorldType = "tfc:tng"

```

**Comment by alcatrazEscapee** [comment] 2023-04-15 22:48
Closing as it's unreproducible and with no further information provided.

**Closed as completed by alcatrazEscapee** 2023-04-15 22:48 UTC
Labels: unconfirmed bug, mod conflict, Version: 1.18.x
