### ISSUE TITLE
Molten Metal inconsistent with lava

### ISSUE THREAD

**Issue by AQUAMEinGithub** [TerraFirmaCraft/TerraFirmaCraft#2821] opened 2024-11-09 11:12 UTC
Molten metal does not burn entities like lava does, nor does it destroy items.

![image](https://github.com/user-attachments/assets/2d30316f-5758-43bc-9c38-2655f286ddb8)

**Comment by alcatrazEscapee** [comment] 2024-11-09 13:37
Duplicate of #2542

**Closed as completed by alcatrazEscapee** 2024-11-09 13:37 UTC
Labels: duplicate
