### ISSUE TITLE
Standing in Leaves Block blocks the ability to drink from rain.

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2109] opened 2022-09-10 17:39 UTC
https://user-images.githubusercontent.com/113080914/189495245-a2507ea6-c49e-4de0-848a-7ba26eaa3199.mp4

**Comment by lumagatto** [comment] 2022-09-10 19:19
in*

**Comment by alcatrazEscapee** [comment] 2022-09-13 22:08
Duplicate of #2119

**Closed as completed by alcatrazEscapee** 2022-09-13 22:08 UTC
Labels: duplicate
