### ISSUE TITLE
Logs don't have inventory models for blocks

### ISSUE THREAD

**Issue by Lumintorious** [TerraFirmaCraft/TerraFirmaCraft#1227] opened 2020-05-08 19:05 UTC
The logs have a 2D model in the inventory but don't have a classic 3D model for general purposes(think vanilla 3D logs) and compatibility (ex. chisels and bits can't chisel them, little tiles chisels them but creates the no-model texture thing)

**Comment by alcatrazEscapee** [comment] 2020-06-12 19:08
So there's two things here:
 - if there's something specific that we do with our item / block model that breaks this, outside of "remove the log item textures", then by all means we can fix this. But I need to know what exactly that would be as as far as I can tell they use pretty bog standard models / blockstates to accomplish this.
 - However, if the problem is just "if they use an item model / texture *for the item* (read: not the block, it functions perfectly fine in world)", then I'd rather not ditch our textures just for this.

I'll also point out it can be quite simply fixed by a resource pack

**Comment by alcatrazEscapee** [comment] 2020-07-29 23:49
After having looking into our block model structure, I don't see anything out of the ordinary. It's all getting thrown away anyway in 1.15+ (due to forge blockstates being removed) so if this is an issue for the time being, use a resource pack. Otherwise, this is a nope.

**Closed as completed by alcatrazEscapee** 2020-07-29 23:49 UTC
Labels: unconfirmed bug, mod conflict
