### ISSUE TITLE
Unworked metal items cannot stack with items that have not been placed in the anvil

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1745] opened 2021-03-22 14:04 UTC
The capability NBT keeps the recipe stored, even if no recipe was selected or no metalworking takes place.

NBT from item that hasn't been in an anvil:
`{"tfc:item_forge":{heat:0.0f,ticks:-1L,forge:{work:0,steps:{last:-1,third:-1,second:-1}}},Parent:{heat:0.0f,ticks:-1L,forge:{work:0,steps:{last:-1,third:-1,second:-1}}}}`

NBT from an item that has been in an anvil:
`{"tfc:item_forge":{heat:0.0f,ticks:-1L,forge:{work:0,steps:{last:-1,third:-1,second:-1}}},Parent:{heat:0.0f,ticks:-1L,forge:{work:0,recipe:"tfc:trapdoor_gold",steps:{last:-1,third:-1,second:-1}}}}`

Seems to only happen on metal items that have a single recipe, since the recipe is automatically selected when put in. Also happens if you select a recipe and don't work it at all.

**Meta Info**
 - TFC Version: 1.7.17.175
 - No mods

**Comment by alcatrazEscapee** [comment] 2021-03-23 00:04
Duplicate of #1586

**Closed as completed by alcatrazEscapee** 2021-03-23 00:04 UTC
Labels: duplicate
