### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#926] opened 2020-03-29 16:49 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
No.
2. What actually happened instead (i.e. what was the bug)
Crashed when trying to view mold recipes in crucible.
3. If it was a crash, upload the full log file (`latest.log`)
https://paste.dimdev.org/axazazufim.mccrash

**To Reproduce**
Search for molds and look at recipes in JEI, it could be a conflict with non TFC fluids, I had GregTech Community Edition installed, so it's best to test it with that.

**Meta Info**
 - TFC Version: 1.12.2-0.30.3.124

**Comment by alcatrazEscapee** [comment] 2020-03-29 16:54
Duplicate of #840

**Closed as completed by alcatrazEscapee** 2020-03-29 16:54 UTC
Labels: duplicate
