### ISSUE TITLE
FallableBlocks destroy LooseItems doesn't appear to work.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#902] opened 2020-03-21 19:39 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
This feature (on by default) to destroy dropped items.
 `` # If true, fallable blocks (ie: dirt, stone) will never destroy loose items.
    B:disableFallableBlocksDestroyLooseItems=false``
2. What actually happened instead (i.e. what was the bug)
Doesn't destroy dropped items.

**Meta Info**
 - TFC Version: 1.12.2-29.5.120

**Comment by DisasterMoo** [comment] 2020-03-21 23:53
Found out the cause. It is a bit conditional, ~~since it pushes around entities, only when the item is blocked from moving away it is then destroyed it seems.~~
Actually, it seems to be a condition i did for applying damage only if block fall from at least 2 blocks tall (since it would be annoying to receive too little damage from a lot of blocks in a cave in), fixed in dev.

**Closed as completed** 2020-03-24 15:40 UTC
Labels: bug, fixed in dev
