### ISSUE TITLE
Can’t receive animal products regardless of familiarity

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#596] opened 2019-11-29 14:28 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Be able to milk cows and shear sheep after getting them to receive max familiarity. Also animals seem to be breeding on their own now vs doing it the vanilla way (don’t know if this is intended)
2. What actually happened instead (i.e. what was the bug) animals can’t be used to receive otherwise unobtainable materials such as milk or wool 
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do 'get animal to max familiarity’
2. Then do 'try to use a stone knife on a sheep or a wooden bucket on a cow to see it doesn’t work'

**Meta Info**
 - TFC Version: 0.X.X.97
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment] 2019-11-29 14:34
- If you have multiple issues, submit multiple bug reports
 - This is a duplicate of #506, probably related to #507
> Also animals seem to be breeding on their own now vs doing it the vanilla way
Excuse me? And you have what evidence of this?
>  use a stone knife on a sheep
I don't believe this works as it's not shears

**Closed by alcatrazEscapee** 2019-11-29 14:34 UTC
Labels: unconfirmed bug
