### ISSUE TITLE
Crash after opening small vessel GUI

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#466] opened 2019-09-28 00:46 UTC
Opened up the vessel and was about to move stuff into it when the game suddenly froze and crashed. Using latest version # 76
[crash-2019-09-27_22.13.12-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3664911/crash-2019-09-27_22.13.12-server.txt)

**Comment by Flaksmith** [comment] 2019-09-28 00:51
After testing again it seems to be caused by me shift-clicking items into the vessel.

**Comment by alcatrazEscapee** [comment] 2019-09-28 01:19
Seems to be a duplicate of #426

**Closed** 2019-09-28 01:19 UTC
Labels: duplicate
