### ISSUE TITLE
Barrel overhaul.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1085] opened 2020-04-23 03:29 UTC
TFC 133
Currently barrels are missing some classic features #493 and act kinda odd for finite fluids #1079. Also clicking a sealed barrel on another open filled container will replace the contents of the barrel with whatever is inside the other container.

After talking with a few people in discord a new system was thought up.

Barres must be sealed to pick up with contents, otherwise contents are lost.
Sealed barres can't interact with anything and must be opened to interact with other stuff. Click to collect, Shift click to empty.
Moving with an open barrel will lose a configured amount of liquid that's placed on the entity.
Jumping makes the barrel lose a larger amount.

This would bring barrels in line with everything else in the modded world for fluid containers along with improving how they operate with the ideas of TFC.

**Comment by alcatrazEscapee** [comment] 2020-07-29 23:48
This is kinda a mega issue for a bunch of smaller problems. 

- #493 is an issue nobody's cared enough to fix (it underlies a more endemic problem which is that barrels don't act as containers as items)
- #1079 is working as intended and will not change as a result of this or other changes.

I'm going to close this in favor of #493 as it's closer to solving the actual problem (giving barrels fluid container capability). More issues have been brought up recently concerning the inability to move fluids with low amounts (as everything is a full-or-nothing container with a specific volume, which does not work well with the structure of barrel recipes).

**Closed as completed by alcatrazEscapee** 2020-07-29 23:48 UTC
Labels: enhancement
