### ISSUE TITLE
Quern Duplication Bug

### ISSUE THREAD

**Issue by firemaster1294** [TerraFirmaCraft/TerraFirmaCraft#2514] opened 2023-09-28 08:41 UTC
TFC Version: 2.2.30
Forge Version: 40.2.10
Minecraft Version: 1.18.2

I have discovered a cheeky way of getting duplicate dyes or powder from the quern:
Step 1. insert at least 2 of the processing item (example: dandelions)
Step 2. process the first item. (example: two yellow dye will be here now)
Step 3. start processing the next item and while this happens, click the output from before to collect it (example: no output will be left now)
Step 4. observe as the output you have consumed magically reappears so you can collect it again along with the next output (example: four yellow dye will be here now)

Rinse and repeat, this can allow you to gain more output than you should be able to get (in the example: first 2, then 6, then 12, then 20...)

**Comment by alcatrazEscapee** [comment] 2023-09-28 15:58
I can't reproduce. The quern does not allow you to extract output (or interact in any way) while processing:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/26864b74d586b350cdbe877c983fa7946fc3c186/src/main/java/net/dries007/tfc/common/blocks/devices/QuernBlock.java#L139

Are you using any other mods? Did you reproduce this on singleplayer or multiplayer (and if the latter, with what server software?) Can you upload a full `latest.log` file from a run where this issue occurs?

**Comment by alcatrazEscapee** [comment] 2023-11-02 01:53
Closing as unreproducible given the lack of a response.

**Closed as not planned by alcatrazEscapee** 2023-11-02 01:53 UTC
Labels: unconfirmed bug, Version: 1.18.x
