### ISSUE TITLE
Wolves and Direwolves stuck in their sleeping animation but still move

### ISSUE THREAD

**Issue by Duck986** [TerraFirmaCraft/TerraFirmaCraft#2483] opened 2023-07-27 17:22 UTC
Video: https://tempclip.com/wQk4v7Fi6VOHTkJ/watch

I'm not sure how this works, but sometimes I randomly find wolves that move or attack while in their sleeping animation

**Comment by h4ppyboy** [comment] 2023-08-16 22:08
Cringe bug, getting attacked by sleeping bears, sabretooths and direwolves getting me mad

**Comment by eerussianguy** [comment] 2023-08-25 15:29
Duplicate of #2354

**Closed as completed by eerussianguy** 2023-08-25 15:29 UTC
Labels: duplicate, unconfirmed bug, Version: 1.18.x
