### ISSUE TITLE
Path doesn't support adjacent dirt

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#679] opened 2019-12-19 12:18 UTC
**Describe the bug**
Path doesn't support adjacent dirt. Expected to be able to place dirt in the gap in the picture and it not to not fall.

**Meta Info**
 - TFC Version: 0.X.X.107
 
![2019-12-19_11 32 48](https://user-images.githubusercontent.com/58256171/71173028-9aa28f80-2259-11ea-99fe-a6144aae1add.png)

**Comment by alcatrazEscapee** [comment] 2019-12-19 12:50
Duplicate of #564

**Closed by alcatrazEscapee** 2019-12-19 12:50 UTC
Labels: unconfirmed bug
