### ISSUE TITLE
Records reporting delays

### ISSUE THREAD

**Issue by TsplayerT** [TerraFirmaCraft/TerraFirmaCraft#1689] opened 2021-02-15 22:23 UTC
I had opened an issue (#1681) to discuss it but testing it ONLY with TerraFirmaCraft again showed this information:

```
[Server thread/INFO] [tfc]: World time and Calendar Time are out of sync! Trying to fix...
[Server thread/INFO] [tfc]: Calendar Time = 966858 (858), Player Time = 844, World Time = 860, doDaylightCycle = true, ArePlayersLoggedOn = true
[Server thread/INFO] [tfc]: Calendar is behind by 2 ticks, jumping calendar time to catch up
```

**Comments:**
• I had previously tested with TLauncher now I switched to ShiginimaLauncher but again I had the same problem.
• I downloaded everything again from Assets, Libraries and Forge, the entire ```.minecraft``` folder.
• Always generating a new world with each new test.

JVM arguments: ```-Xmx5G```
JRE version: 1.8.0_261
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
TerraFirmaCraft version: 1.12.2-1.7.11.169

Log file: [latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5984376/latest.log)

**Comment by alcatrazEscapee** [comment] 2021-02-15 22:38
Duplicate of #1681 then.

In case it wasn't clear in my last comment, you are opening an issue about nothing. That log message is not the cause of an issue and is entirely expected.

**Closed as completed by alcatrazEscapee** 2021-02-15 22:38 UTC
Labels: duplicate, working as intended
