### ISSUE TITLE
Ore inside vessel does not melt in forge

### ISSUE THREAD

**Issue by cronsOP125** [TerraFirmaCraft/TerraFirmaCraft#795] opened 2020-02-08 00:24 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Ore inside a vessel would melt when placed into a forge and heated to brilliant white
2. What actually happened instead (i.e. what was the bug) Vessel heated to brilliant white, ore inside remained unheated.
3. If it was a crash, upload the full log file (`latest.log`) No crash.
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do place ore into small vessel
2. Then do place vessel into lit forge
3. Then do heat vessel to brilliant white.

**Meta Info**
 - TFC Version: 0.29.0.115
 - Were any other mods included? Inventory Tweaks, Xaero's Minimap
   Can you reproduce it without these other mods? Yes
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment] 2020-02-13 17:14
Not sure if it was related to #781, but I can't reproduce in 116.

**Comment by alcatrazEscapee** [comment] 2020-02-18 15:49
Can't reproduce, closing unless it's reoccurring.

**Closed as completed by alcatrazEscapee** 2020-02-18 15:49 UTC
Labels: unconfirmed bug
