### ISSUE TITLE
Time is not progressing 

### ISSUE THREAD

**Issue by Rikkertvdwal** [TerraFirmaCraft/TerraFirmaCraft#2640] opened 2024-02-16 21:45 UTC
Playing in my world and the time stopped progressing but plants and other things are still growing.
playing on 1.18.2 java 
using this mod pack wich includes Terra firma craft https://www.curseforge.com/minecraft/modpacks/terrafirmacraft-experience/files/all?page=1&pageSize=20  From what i understand it has the most recent version of tft. 
I would really love some help solving this problem because i dont wanna lose this world or have it happen again.

**Comment by alcatrazEscapee** [comment] 2024-02-17 13:25
Duplicate of https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2562

**Closed as completed by alcatrazEscapee** 2024-02-17 13:25 UTC
Labels: duplicate
