### ISSUE TITLE
Server crashes when logging in

### ISSUE THREAD

**Issue by Hg-Spark** [TerraFirmaCraft/TerraFirmaCraft#2453] opened 2023-06-12 17:11 UTC
Server core : CatServer-1.18.2-6c3f5965-server
Forge : 40.2.4
Server reports errors though doesn't crash when initiating
![TB I5)}B0) Q@F4X31E}(28](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/46282235/76902aab-6e28-48dc-bc9a-9f371997b9e5)
When I try to login in server, it will crash

Here are logs

[debug.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11726047/debug.log)
[crash-2023-06-13_01.07.30-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11726056/crash-2023-06-13_01.07.30-server.txt)
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11726048/latest.log)

**Comment by alcatrazEscapee** [comment] 2023-06-12 17:18
Duplicate of #2444

**Closed as not planned by alcatrazEscapee** 2023-06-12 17:18 UTC
Labels: duplicate
