### ISSUE TITLE
Crash when trying to get recipe

### ISSUE THREAD

**Issue by drago87** [TerraFirmaCraft/TerraFirmaCraft#900] opened 2020-03-20 18:20 UTC
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Show the recipe
2. What actually happened instead (i.e. what was the bug) Game crash
3. If it was a crash, upload the full log file (`latest.log`)
[latest.log](https://gist.github.com/drago87/a43213c1a57a3cdf4def03dd4bcc9f59)
["vanilla" crashlog](https://pastebin.com/LuvaAsM2)
[VanillaFix crashlog](https://paste.dimdev.org/poyavaliyi.mccrash)
[OpenEye Crash log](http://openeye.openmods.info/crashes/2150b3cd31f3328816e34d372ee57d46)
4. If they would help to explain the issue, include screenshots
![VanillaFix Crash](https://user-images.githubusercontent.com/6805712/77193566-c2b2c080-6ade-11ea-9e3c-484f49d3ccfc.png)

**To Reproduce**
Attention to detail is important!
1. Do 'open jei and find bismuth ingot'
2. Then do 'press 'r' on the ingot'
3. Then do 'press 'r' on the mold and go to the "Casting recipes" tab' and the game crashes

**Meta Info**
 - TFC Version: MC1.12.2-29.5.120
 - Here is a link to all mods with config and scripts. I have not been able to find what mod/mods conflict but will continue to search for it
[Dropbox modpack](https://www.dropbox.com/sh/sj6mga7ha6sc3qd/AAAvEgIOdvKGoT4Nx9pebhH1a?dl=0)

**Comment by alcatrazEscapee** [comment] 2020-03-20 18:25
Duplicate of #840

**Closed as completed by alcatrazEscapee** 2020-03-20 18:25 UTC
Labels: duplicate
