### ISSUE TITLE
Cannot load from int array because "this.surfaceHeight" is null (But different)

### ISSUE THREAD

**Issue by AtobaAzul** [TerraFirmaCraft/TerraFirmaCraft#2731] opened 2024-06-19 00:26 UTC
_Versions:_
**MC** - 1.20.1
**TFC** - 3.2.4
**Forge** - 47.2.6

The [original issue](https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2661#issue-2177462855) regarding this crash mentions it is caused by Distant Horizons and it is tagged with Mod Conflict.
After some testing with DH settings, both turning off distant generation as well as rendering, I decided to turn off DH _entirely_ from the mods and the crash still happens.

[Crash Log](https://pastebin.com/A4PjtVus)

**Comment by eerussianguy** [comment] 2024-06-19 02:30
Does the crash happen on a new world?

**Comment by eerussianguy** [comment] 2024-06-19 02:31
Also you have sinatra connector installed... which does not bode well for us being able to debug your problem.

**Comment by AtobaAzul** [comment] 2024-06-19 11:51
[Crash with no DH and Connector](https://pastebin.com/sPCM5H7x)

Doesn't happen on a new world; or at least, didn't happen yet. I tried reproducing but to get this crash in the first place I had played on the world for over 4 hours.

**Comment by alcatrazEscapee** [comment] 2024-06-19 12:35
The crash is due to your world having (essentially) corrupted chunks with missing data. If you remove DH, it will still crash. The root cause, as far as we know, is still the same.

Duplicate of #2661

**Closed as not planned by alcatrazEscapee** 2024-06-19 12:35 UTC
Labels: duplicate
