### ISSUE TITLE
Patchouli Predator Error Crash

### ISSUE THREAD

**Issue by cole4114** [TerraFirmaCraft/TerraFirmaCraft#1545] opened 2020-08-26 23:56 UTC
**Describe the bug**
1. Patchouli - within the book guide under getting started predators and the thrill of the hunt buttons to open.
2. When opening the book initially it shows 2 errors for "predators" and "predators page 1" with pressing the buttons specified above it crashes the game to desktop.
3. [latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5133192/latest.log)
Direct crash log: [crash-2020-08-26_18.48.45-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5133208/crash-2020-08-26_18.48.45-client.txt)
4. [2020-08-26_18 50 23](https://user-images.githubusercontent.com/34220637/91367808-0cf64700-e7cd-11ea-8996-d32e740a8fea.png)

**To Reproduce**
1. Open the book go into "Getting Started"
2. Then press "Predators" or "The Thrill of the Hunt"

**Meta Info**
 - TFC Version: 1.7.0.158
 - Patchouli was the only other mod, and no it can not be reproduced without it.
 - Patchouli 1.0-21

**Comment by alcatrazEscapee** [comment] 2020-08-27 00:16
Likely duplicate of #1541

**Closed as completed by alcatrazEscapee** 2020-08-27 00:16 UTC
Labels: duplicate
